#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/albion/tmp/app' $INSTALL_DIR'/albion/game'
rm -R -f $INSTALL_DIR'/albion/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/albion
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/albion/game \
$HOME/.games_nebula/games/.dosbox/albion
python $NEBULA_DIR/launcher_dosbox.py albion' > \
$INSTALL_DIR'/albion/start.sh'
chmod +x $INSTALL_DIR'/albion/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/albion
imgmount d $HOME/.games_nebula/games/.dosbox/albion/game.gog -t iso
c:
cls
albion.exe
exit" > $INSTALL_DIR'/albion/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/albion
imgmount d $HOME/.games_nebula/games/.dosbox/albion/game.gog -t iso
c:
cls
setup.exe
exit" > $INSTALL_DIR'/albion/dosbox_settings.conf'
