#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/saints_row_iv_game_of_the_century_edition/tmp/app' \
$INSTALL_DIR'/saints_row_iv_game_of_the_century_edition/game'
rm -R -f $INSTALL_DIR'/saints_row_iv_game_of_the_century_edition/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py saints_row_iv_game_of_the_century_edition "Saints Row IV.exe"' > \
$INSTALL_DIR'/saints_row_iv_game_of_the_century_edition/start.sh'
chmod +x $INSTALL_DIR'/saints_row_iv_game_of_the_century_edition/start.sh'
