#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/vvvvvv/tmp/data/noarch/'* $INSTALL_DIR'/vvvvvv/'
rm -R -f $INSTALL_DIR'/vvvvvv/tmp'
mv $INSTALL_DIR'/vvvvvv/start.sh' $INSTALL_DIR'/vvvvvv/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ $(uname -m) == "x86_64" ]; then
    #export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/x86_64"
    cd "$DIR/game/x86_64"
    "./vvvvvv.x86_64"
else
    #export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/x86"
    cd "$DIR/game/x86"
    "./vvvvvv.x86"
fi'> $INSTALL_DIR'/vvvvvv/start_gn.sh'
chmod +x $INSTALL_DIR'/vvvvvv/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py vvvvvv' > \
$INSTALL_DIR'/vvvvvv/start.sh'
chmod +x $INSTALL_DIR'/vvvvvv/start.sh'
