#!/bin/bash

echo -e '#!/bin/bash
rm "$WINEPREFIX/drive_c/users/$USER/Local Settings/Application Data/THQ/Saints Row 2/settings.dat"
mkdir -p "$WINEPREFIX/drive_c/users/$USER/Local Settings/Application Data/THQ/Saints Row 2"
ln -s "$INSTALL_DIR/$GAME_NAME/game/settings.dat" \
"$WINEPREFIX/drive_c/users/$USER/Local Settings/Application Data/THQ/Saints Row 2/settings.dat"' > \
"$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"
