#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/saints_row_2/tmp/game' $INSTALL_DIR'/saints_row_2/game'
rm -R -f $INSTALL_DIR'/saints_row_2/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py saints_row_2 SR2_pc.exe' > \
$INSTALL_DIR'/saints_row_2/start.sh'
chmod +x $INSTALL_DIR'/saints_row_2/start.sh'
