#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/little_big_adventure/tmp/app' $INSTALL_DIR'/little_big_adventure/game'
rm -R -f $INSTALL_DIR'/little_big_adventure/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/little_big_adventure
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/little_big_adventure/game \
$HOME/.games_nebula/games/.dosbox/little_big_adventure
python $NEBULA_DIR/launcher_dosbox.py little_big_adventure' > \
$INSTALL_DIR'/little_big_adventure/start.sh'
chmod +x $INSTALL_DIR'/little_big_adventure/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/little_big_adventure
imgmount d $HOME/.games_nebula/games/.dosbox/little_big_adventure/LBA.DAT -t iso
c:
cls
mixer cdaudio 50:50
RELENT.EXE
exit" > $INSTALL_DIR'/little_big_adventure/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/little_big_adventure
imgmount d $HOME/.games_nebula/games/.dosbox/little_big_adventure/LBA.DAT -t iso
c:
cls
mixer cdaudio 50:50
setup.EXE
cls
exit" > $INSTALL_DIR'/little_big_adventure/dosbox_settings.conf'
