#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/oddworld_abes_exoddus/tmp/app' $INSTALL_DIR'/oddworld_abes_exoddus/game'
rm -R -f $INSTALL_DIR'/oddworld_abes_exoddus/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py oddworld_abes_exoddus Exoddus.exe' > \
$INSTALL_DIR'/oddworld_abes_exoddus/start.sh'
chmod +x $INSTALL_DIR'/oddworld_abes_exoddus/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/oddworld_abes_exoddus
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/oddworld_abes_exoddus/game \
$WINEPREFIX_DIR/drive_c/Games/oddworld_abes_exoddus' > \
$INSTALL_DIR'/oddworld_abes_exoddus/additions.sh'
chmod +x $INSTALL_DIR'/oddworld_abes_exoddus/additions.sh'
