#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/prince_of_persia_the_two_thrones/tmp/app' \
$INSTALL_DIR'/prince_of_persia_the_two_thrones/game'
rm -R -f $INSTALL_DIR'/prince_of_persia_the_two_thrones/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py prince_of_persia_the_two_thrones PrinceOfPersia.exe' > \
$INSTALL_DIR'/prince_of_persia_the_two_thrones/start.sh'
chmod +x $INSTALL_DIR'/prince_of_persia_the_two_thrones/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia The Two Thrones\\1.00.999" /v \
"Product_Executable" /t REG_SZ /d PrinceOfPersia.exe /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia The Two Thrones\\1.00.999" /v \
"Product_Language" /t REG_SZ /d "9" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia The Two Thrones\\1.00.999" /v \
"Product_Path" /t REG_SZ /d $INSTALL_DIR_WIN\\\\prince_of_persia_the_two_thrones\\\\game /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia The Two Thrones\\1.00.999" /v \
"Product_Release" /t REG_SZ /d "Retail EMEA" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia The Two Thrones\\1.00.999" /v \
"Profiles_Path" /t REG_SZ /d $INSTALL_DIR_WIN\\\\prince_of_persia_the_two_thrones\\\\game /f

rm $WINEPREFIX_DIR/drive_c/Games/prince_of_persia_the_two_thrones
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/prince_of_persia_the_two_thrones/game \
$WINEPREFIX_DIR/drive_c/Games/prince_of_persia_the_two_thrones' > \
$INSTALL_DIR'/prince_of_persia_the_two_thrones/additions.sh'
chmod +x $INSTALL_DIR'/prince_of_persia_the_two_thrones/additions.sh'
