#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_upx

cd "$INSTALL_DIR/$GAME_NAME/game"
./upx -d pop3.exe

get_from_mega 'pop3_widescreen.7z' \
'https://mega.nz/#!WEoWXaxZ!YBu3pugXDpR5iQvCKqxcAXHE8Bn3RKKjXFpuxWPzXZc'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/pop3_widescreen.7z" \
'pop3.7z'

7z x -aoa -p'pop3' -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$INSTALL_DIR/$GAME_NAME/game/pop3.7z"
