#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'alone_in_the_dark_3' \
'https://images-3.gog.com/92a2cbda2d08f3d411c65a22173d8dbe261aa0a69d70f6eeb3493884a0879556.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/alone_in_the_dark_3/tmp/app' $INSTALL_DIR'/alone_in_the_dark_3/game'
rm -R -f $INSTALL_DIR'/alone_in_the_dark_3/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/alone_in_the_dark_3/game \
$HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3
python $NEBULA_DIR/launcher_dosbox.py alone_in_the_dark_3' > \
$INSTALL_DIR'/alone_in_the_dark_3/start.sh'
chmod +x $INSTALL_DIR'/alone_in_the_dark_3/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3
c:
imgmount d $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3/game.ins -fs iso
cls
CD INDARK3
AITD3
exit" > $INSTALL_DIR'/alone_in_the_dark_3/dosbox_game.conf'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3
c:
imgmount d $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_3/game.ins -fs iso
cls
CD INDARK3
INSTALL
exit" > $INSTALL_DIR'/alone_in_the_dark_3/dosbox_settings.conf'
