#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/tmp/app' \
$INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/game'
rm -R -f $INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py \
leisure_suit_larry_magna_cum_laude_uncut_and_uncensored Larry.exe' > \
$INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/start.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/game \
$WINEPREFIX_DIR/drive_c/Games/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored' > \
$INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/additions.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_magna_cum_laude_uncut_and_uncensored/additions.sh'
