#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_file 'popres.exe' \
'https://www.popre.net/files/popres.exe'
cp "$DOWNLOAD_DIR/_distr/$GAME_NAME/popres.exe" "$INSTALL_DIR/$GAME_NAME/game/"
