#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/hotline_miami/tmp/data/noarch/'* $INSTALL_DIR'/hotline_miami/'
rm -R -f $INSTALL_DIR'/hotline_miami/tmp'
mv $INSTALL_DIR'/hotline_miami/start.sh' $INSTALL_DIR'/hotline_miami/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./hotline_launcher"' > $INSTALL_DIR'/hotline_miami/start_gn.sh'
chmod +x $INSTALL_DIR'/hotline_miami/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py hotline_miami' > \
$INSTALL_DIR'/hotline_miami/start.sh'
chmod +x $INSTALL_DIR'/hotline_miami/start.sh'
