#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/costume_quest/tmp/data/noarch/'* \
$INSTALL_DIR'/costume_quest/'
rm -R -f $INSTALL_DIR'/costume_quest/tmp'
mv $INSTALL_DIR'/costume_quest/start.sh' $INSTALL_DIR'/costume_quest/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./Cq.bin.x86"' > $INSTALL_DIR'/costume_quest/start_gn.sh'
chmod +x $INSTALL_DIR'/costume_quest/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py costume_quest' > \
$INSTALL_DIR'/costume_quest/start.sh'
chmod +x $INSTALL_DIR'/costume_quest/start.sh'
