#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_common_file 'LAVFilters-0.69-x86.zip' \
'https://github.com/Nevcairiel/LAVFilters/releases/download/0.69/LAVFilters-0.69-x86.zip'

echo -e 'mkdir -p "$WINEPREFIX/drive_c/Program Files/LAVFilters"
7z x -aoa -o"$WINEPREFIX/drive_c/Program Files/LAVFilters" \
"$DOWNLOAD_DIR/_distr/LAVFilters-0.69-x86.zip"
cd "$WINEPREFIX/drive_c/Program Files/LAVFilters"
"$WINELOADER" regsvr32.exe LAVSplitter.ax
"$WINELOADER" regsvr32.exe LAVVideo.ax
"$WINELOADER" regsvr32.exe LAVAudio.ax' >> \
"$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"

echo -e '#!/bin/bash
export WINEDLLOVERRIDES="d3d8=n,b"
python2 "$NEBULA_DIR/launcher_wine.py" bloodrayne_2 "br2.exe"' > "$START_FILE"
