#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/broken_sword_directors_cut/tmp/data/noarch/'* \
$INSTALL_DIR'/broken_sword_directors_cut/'
rm -R -f $INSTALL_DIR'/broken_sword_directors_cut/tmp'
mv $INSTALL_DIR'/broken_sword_directors_cut/start.sh' \
$INSTALL_DIR'/broken_sword_directors_cut/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ $(uname -m) == "x86_64" ]; then
    #export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/x86_64"
    cd "$DIR/game/"
    "./x86_64/bs1dc_x86_64"
else
    #export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/i386"
    cd "$DIR/game/"
    "./i386/bs1dc_i386"
fi' > $INSTALL_DIR'/broken_sword_directors_cut/start_gn.sh'
chmod +x $INSTALL_DIR'/broken_sword_directors_cut/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py broken_sword_directors_cut' > \
$INSTALL_DIR'/broken_sword_directors_cut/start.sh'
chmod +x $INSTALL_DIR'/broken_sword_directors_cut/start.sh'
