#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'konung_2_blood_of_titans' \
'https://images-2.gog.com/b2dd6b9c3c4abc637738593a26e1d376abefddde921ec2dd467410fdab87ff58.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/konung_2_blood_of_titans/tmp/app' \
$INSTALL_DIR'/konung_2_blood_of_titans/game'
rm -R -f $INSTALL_DIR'/konung_2_blood_of_titans/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/codinstl.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/codinstl.exe'  -C - \
	'http://www.cucusoft.com/codecdownload/codinstl.exe'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

mkdir -p $HOME'/.cache/winetricks/icodecs'
if [ ! -f $HOME'/.cache/winetricks/icodecs/codinstl.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/codinstl.exe' $HOME'/.cache/winetricks/icodecs/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py konung_2_blood_of_titans Konung2.exe' > \
$INSTALL_DIR'/konung_2_blood_of_titans/start.sh'
chmod +x $INSTALL_DIR'/konung_2_blood_of_titans/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

winetricks --gui icodecs quartz

rm $WINEPREFIX_DIR/drive_c/Games/konung_2_blood_of_titans
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/konung_2_blood_of_titans/game \
$WINEPREFIX_DIR/drive_c/Games/konung_2_blood_of_titans' > \
$INSTALL_DIR'/konung_2_blood_of_titans/additions.sh'
chmod +x $INSTALL_DIR'/konung_2_blood_of_titans/additions.sh'
