#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/majesty_gold_hd/tmp/app' $INSTALL_DIR'/majesty_gold_hd/game'
rm -R -f $INSTALL_DIR'/majesty_gold_hd/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'
if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py majesty_gold_hd MajestyHD.exe' > \
$INSTALL_DIR'/majesty_gold_hd/start.sh'
chmod +x $INSTALL_DIR'/majesty_gold_hd/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

winetricks --gui quartz

rm $WINEPREFIX_DIR/drive_c/Games/majesty_gold_hd
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/majesty_gold_hd/game \
$WINEPREFIX_DIR/drive_c/Games/majesty_gold_hd' > \
$INSTALL_DIR'/majesty_gold_hd/additions.sh'
chmod +x $INSTALL_DIR'/majesty_gold_hd/additions.sh'
