#!/bin/bash

INSTALL_DIR=$2

mv "$INSTALL_DIR/renowned_explorers/tmp/data/noarch/"* "$INSTALL_DIR/renowned_explorers/"
rm -R -f "$INSTALL_DIR/renowned_explorers/tmp"
mv "$INSTALL_DIR/renowned_explorers/start.sh" "$INSTALL_DIR/renowned_explorers/start_gog.sh"

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
if [ $(uname -m) == "x86_64" ]; then
    cd "$DIR/game/x86_64"
    ./abbeycore
else
    cd "$DIR/game/x86"
    ./abbeycore
fi' > "$INSTALL_DIR/renowned_explorers/start_gn.sh"
chmod +x "$INSTALL_DIR/renowned_explorers/start_gn.sh"

echo -e '#!/bin/bash
NEBULA_DIR="$2"
python "$NEBULA_DIR/launcher_native.py" renowned_explorers' > \
"$INSTALL_DIR/renowned_explorers/start.sh"
chmod +x "$INSTALL_DIR/renowned_explorers/start.sh"
