#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'softporn_adventure' \
'https://images-3.gog.com/78b0ac88cac77112b26549c7ba3c17a98ecf5a1bc81bdf00e32172cde5deb092.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/softporn_adventure/tmp/data/noarch/data' $INSTALL_DIR'/softporn_adventure/game'
rm -R -f $INSTALL_DIR'/softporn_adventure/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/softporn_adventure
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/softporn_adventure/game \
$HOME/.games_nebula/games/.dosbox/softporn_adventure
python $NEBULA_DIR/launcher_dosbox.py softporn_adventure' > \
$INSTALL_DIR'/softporn_adventure/start.sh'
chmod +x $INSTALL_DIR'/softporn_adventure/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/softporn_adventure
c:
cls
softporn.exe
exit" > $INSTALL_DIR'/softporn_adventure/dosbox_game.conf'
