#!/bin/bash

if [ -d "$INSTALL_DIR/$GAME_NAME/game/MUSIC" ]; then
echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_wine.py" "$GAME_NAME" "KONUNG.EXE"' > "$START_FILE"
else
echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_wine.py" "$GAME_NAME" "konung.exe"' > "$START_FILE"
fi

if [ -d "$INSTALL_DIR/$GAME_NAME/game/MUSIC" ]; then
echo -e '#!/bin/bash
winetricks --gui icodecs quartz' > "$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"
else
echo -e '#!/bin/bash
winetricks --gui wmp9 quartz devenum' > "$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"
fi
