#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/darklands/tmp/data/noarch/data' $INSTALL_DIR'/darklands/game'
mv $INSTALL_DIR'/darklands/tmp/data/noarch/docs/UserManual.pdf' $INSTALL_DIR'/darklands/'
rm -R -f $INSTALL_DIR'/darklands/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/darklands
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/darklands/game \
$HOME/.games_nebula/games/.dosbox/darklands
python $NEBULA_DIR/launcher_dosbox.py darklands' > \
$INSTALL_DIR'/darklands/start.sh'
chmod +x $INSTALL_DIR'/darklands/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/darklands
C:
CD DARKLAND
cls
DARKLAND.EXE 
exit" > $INSTALL_DIR'/darklands/dosbox_game.conf'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/darklands
C:
CD DARKLAND
cls
install
exit" > $INSTALL_DIR'/darklands/dosbox_settings.conf'
