#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/death_to_spies_moment_of_truth/tmp/app' $INSTALL_DIR'/death_to_spies_moment_of_truth/game'
rm -R -f $INSTALL_DIR'/death_to_spies_moment_of_truth/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/scripten.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/scripten.exe'  -C - \
	'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/MPSetup.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/MPSetup.exe'  -C - \
	'http://download.microsoft.com/download/1/b/c/1bc0b1a3-c839-4b36-8f3c-19847ba09299/MPSetup.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe'  -C - \
	'http://birds.camden.rutgers.edu/WM9Codecs9x.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' -C - \
	'http://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

mkdir -p $HOME'/.cache/winetricks/wsh57'
if [ ! -f $HOME'/.cache/winetricks/wsh57/scripten.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/scripten.exe' $HOME'/.cache/winetricks/wsh57/'
fi

mkdir -p $HOME'/.cache/winetricks/wmp9'
if [ ! -f $HOME'/.cache/winetricks/wmp9/MPSetup.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/MPSetup.exe' $HOME'/.cache/winetricks/wmp9/'
fi

mkdir -p $HOME'/.cache/winetricks/wm9codecs'
if [ ! -f $HOME'/.cache/winetricks/wm9codecs/WM9Codecs9x.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe' $HOME'/.cache/winetricks/wm9codecs/'
fi

mkdir -p $HOME'/.cache/winetricks/vcrun2005'
if [ ! -f $HOME'/.cache/winetricks/vcrun2005/vcredist_x86.EXE' ]; then
	cp $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' $HOME'/.cache/winetricks/vcrun2005/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py death_to_spies_moment_of_truth Truth.exe' > \
$INSTALL_DIR'/death_to_spies_moment_of_truth/start.sh'
chmod +x $INSTALL_DIR'/death_to_spies_moment_of_truth/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/death_to_spies_moment_of_truth/game
$WINELOADER TruthSetup.exe' > \
$INSTALL_DIR'/death_to_spies_moment_of_truth/settings.sh'
chmod +x $INSTALL_DIR'/death_to_spies_moment_of_truth/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

winetricks --gui vcrun2005 wmp9 devenum quartz d3dx9

rm $WINEPREFIX_DIR/drive_c/Games/death_to_spies_moment_of_truth
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/death_to_spies_moment_of_truth/game \
$WINEPREFIX_DIR/drive_c/Games/death_to_spies_moment_of_truth' > \
$INSTALL_DIR'/death_to_spies_moment_of_truth/additions.sh'
chmod +x $INSTALL_DIR'/death_to_spies_moment_of_truth/additions.sh'
