#!/bin/bash

DOWNLOAD_DIR="$1"
INSTALL_DIR="$2"
NEBULA_DIR="$3"

python2 "$NEBULA_DIR/modules/goglib_get_banner_2.py" \
'ultima_vii_serpent_isle' \
'https://images-1.gog.com/4ebc27b7c4c9d1907159d3e2b2d0a61c60510006ab83222f3d79606ac7e26b3e.jpg' \
"$HOME/.games_nebula/images/goglib_banners"

mv "$INSTALL_DIR/ultima_vii_serpent_isle/tmp/app" \
"$INSTALL_DIR/ultima_vii_serpent_isle/game"
rm -R -f "$INSTALL_DIR/ultima_vii_serpent_isle/tmp"

VER=$(zenity --list \
--hide-header \
--title "Ultima 7" \
--text "Play using:" \
--column Software \
"DOSBox" \
"Exult")

if [ "$VER" == "DOSBox" ]; then

echo '#!/bin/bash
INSTALL_DIR="$1"
NEBULA_DIR="$2"
rm "$HOME/.games_nebula/games/.dosbox/ultima_vii_serpent_isle"
mkdir -p "$HOME/.games_nebula/games/.dosbox"
ln -s "$INSTALL_DIR/ultima_vii_serpent_isle/game" \
"$HOME/.games_nebula/games/.dosbox/ultima_vii_serpent_isle"
python "$NEBULA_DIR/launcher_dosbox.py" ultima_vii_serpent_isle' > \
"$INSTALL_DIR/ultima_vii_serpent_isle/start.sh"
chmod +x "$INSTALL_DIR/ultima_vii_serpent_isle/start.sh"

echo "[dos]
ems=false
[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/ultima_vii_serpent_isle
c:
cls
serpent.com
cls
exit" > "$INSTALL_DIR/ultima_vii_serpent_isle/dosbox_game.conf"

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/ultima_vii_serpent_isle
c:
cls
install.exe
cls
exit" > "$INSTALL_DIR/ultima_vii_serpent_isle/dosbox_settings.conf"

fi

if [ "$VER" == "Exult" ]; then

mkdir -p "$INSTALL_DIR/exult/data"
mkdir -p "$INSTALL_DIR/exult/saves"
mkdir -p "$DOWNLOAD_DIR/_distr/ultima_7"

if [ ! -f "$DOWNLOAD_DIR/_distr/ultima_7/"* ]; then
    curl -L -o "$DOWNLOAD_DIR/_distr/ultima_7/exult_1.5.0_git_bdcce09_gcc_4.9.2_amd64.tar.gz" -C - \
    'https://github.com/yancharkin/exult/releases/download/1.5.0git/exult_1.5.0_git_bdcce09_gcc_4.9.2_amd64.tar.gz'
    curl -L -o "$DOWNLOAD_DIR/_distr/ultima_7/exult_1.5.0_git_bdcce09_gcc_4.9.2_i386.tar.gz" -C - \
    'https://github.com/yancharkin/exult/releases/download/1.5.0git/exult_1.5.0_git_bdcce09_gcc_4.9.2_i386.tar.gz'
fi

if [ ! -d "$INSTALL_DIR/exult/bin" ]; then
if [ $(uname -m) == "x86_64" ]; then
    tar -xzvf "$DOWNLOAD_DIR/_distr/ultima_7/exult_1.5.0_git_bdcce09_gcc_4.9.2_amd64.tar.gz" \
    -C "$INSTALL_DIR/exult"
else
    tar -xzvf "$DOWNLOAD_DIR/_distr/ultima_7/exult_1.5.0_git_bdcce09_gcc_4.9.2_i386.tar.gz" \
    -C "$INSTALL_DIR/exult"
fi
fi

zenity --question \
--title "Ultima 7" \
--text "Download and install Audio Data packs?" \
--ok-label "Yes" --cancel-label "No"   

if [ $? == 0 ]; then
if [ ! -f "$DOWNLOAD_DIR/_distr/ultima_7/exult_audio.zip" ]; then
    curl -L -o "$DOWNLOAD_DIR/_distr/ultima_7/exult_audio.zip" -C - \
    'http://prdownloads.sourceforge.net/exult/exult_audio.zip' | \
    zenity --progress --title "Neverwinter Nights" --text \
    "Downloading exult_audio.zip..." --auto-close --no-cancel --pulsate
fi
7z x -aoa -o"$INSTALL_DIR/exult/share/exult" \
"$DOWNLOAD_DIR/_distr/ultima_7/exult_audio.zip"
fi

rm -r "$INSTALL_DIR/exult/data/silverseed"
ln -s "$INSTALL_DIR/ultima_vii_serpent_isle/game" \
"$INSTALL_DIR/exult/data/silverseed"

echo '#!/bin/bash
INSTALL_DIR="$1"
"$INSTALL_DIR/exult/bin/exult" -c "$INSTALL_DIR/exult/exult.cfg"' > \
"$INSTALL_DIR/ultima_vii_serpent_isle/start.sh"
chmod +x "$INSTALL_DIR/ultima_vii_serpent_isle/start.sh"

if [ ! -f "$INSTALL_DIR/exult/exult.cfg" ]; then

echo -e "<config>
 <disk>
  <data_path>
  $INSTALL_DIR/exult/share/exult
  </data_path>
  <game>
   <blackgate>
    <path>
    $INSTALL_DIR/exult/data/blackgate
    </path>
    <static_path>
    $INSTALL_DIR/exult/data/blackgate/static
    </static_path>
    <savegame_path>
    $INSTALL_DIR/exult/saves/blackgate
    </savegame_path>
    <gamedat_path>
    $INSTALL_DIR/exult/saves/blackgate
    </gamedat_path>
   </blackgate>
   <forgeofvirtue>
    <path>
    $INSTALL_DIR/exult/data/forgeofvirtue
    </path>
    <static_path>
    $INSTALL_DIR/exult/data/forgeofvirtue/static
    </static_path>
    <savegame_path>
    $INSTALL_DIR/exult/saves/forgeofvirtue
    </savegame_path>
    <gamedat_path>
    $INSTALL_DIR/exult/saves/forgeofvirtue
    </gamedat_path>
   </forgeofvirtue>
   <serpentisle>
    <path>
    $INSTALL_DIR/exult/data/serpentisle
    </path>
    <static_path>
    $INSTALL_DIR/exult/data/serpentisle/static
    </static_path>
    <savegame_path>
    $INSTALL_DIR/exult/saves/serpentisle
    </savegame_path>
    <gamedat_path>
    $INSTALL_DIR/exult/saves/serpentisle
    </gamedat_path>
   </serpentisle>
   <silverseed>
    <path>
    $INSTALL_DIR/exult/data/silverseed
    </path>
    <static_path>
    $INSTALL_DIR/exult/data/silverseed/static
    </static_path>
    <savegame_path>
    $INSTALL_DIR/exult/saves/silverseed
    </savegame_path>
    <gamedat_path>
    $INSTALL_DIR/exult/saves/silverseed
    </gamedat_path>
   </silverseed>
   <serpentbeta>
    <path>
    $INSTALL_DIR/exult/data/serpentbeta
    </path>
    <static_path>
    $INSTALL_DIR/exult/data/serpentbeta/static
    </static_path>
    <savegame_path>
    $INSTALL_DIR/exult/saves/serpentbeta
    </savegame_path>
    <gamedat_path>
    $INSTALL_DIR/exult/saves/serpentbeta
    </gamedat_path>
   </serpentbeta>
   </game>
 </disk>
</config>" > "$INSTALL_DIR/exult/exult.cfg" 
fi
fi
