#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/saints_row_the_third_the_full_package/tmp/game' \
$INSTALL_DIR'/saints_row_the_third_the_full_package/game'
mv $INSTALL_DIR'/saints_row_the_third_the_full_package/tmp/language_setup/language_setup.exe' \
$INSTALL_DIR'/saints_row_the_third_the_full_package/game/'
mv $INSTALL_DIR'/saints_row_the_third_the_full_package/tmp/support/app/'* \
$INSTALL_DIR'/saints_row_the_third_the_full_package/game/'
rm -R -f $INSTALL_DIR'/saints_row_the_third_the_full_package/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py saints_row_the_third_the_full_package game_launcher.exe' > \
$INSTALL_DIR'/saints_row_the_third_the_full_package/start.sh'
chmod +x $INSTALL_DIR'/saints_row_the_third_the_full_package/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
        export WINELOADER=$WINE_DIR
        export WINEPREFIX=$WINEPREFIX_DIR
else
        export WINE=$WINE_DIR/bin/wine
        export WINELOADER=$WINE_DIR/bin/wine
        export WINESERVER=$WINE_DIR/bin/wineserver
        export WINEDLLPATH=$WINE_DIR/lib
        export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/saints_row_the_third_the_full_package/game
$WINELOADER language_setup.exe' > \
$INSTALL_DIR'/saints_row_the_third_the_full_package/settings.sh'
chmod +x $INSTALL_DIR'/saints_row_the_third_the_full_package/settings.sh'
