#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/tmp/app' \
$INSTALL_DIR'/worlds_of_ultima_the_savage_empire/game'
rm -R -f $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/tmp'

mkdir -p $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/game/SAVAGE/SAVEGAME/'
cp $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/game/__support/save/SAVAGE/SAVEGAME/'* \
$INSTALL_DIR'/worlds_of_ultima_the_savage_empire/game/SAVAGE/SAVEGAME/'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/worlds_of_ultima_the_savage_empire
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/worlds_of_ultima_the_savage_empire/game \
$HOME/.games_nebula/games/.dosbox/worlds_of_ultima_the_savage_empire
python $NEBULA_DIR/launcher_dosbox.py worlds_of_ultima_the_savage_empire' > \
$INSTALL_DIR'/worlds_of_ultima_the_savage_empire/start.sh'
chmod +x $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/worlds_of_ultima_the_savage_empire
c:
cd SAVAGE
cls
SAVAGE.EXE
exit" > $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/worlds_of_ultima_the_savage_empire
c:
cd SAVAGE
cls
INSTALL.EXE
exit" > $INSTALL_DIR'/worlds_of_ultima_the_savage_empire/dosbox_settings.conf'
