#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_common_file 'Old_Games_Widescreen_Patch.rar' \
'https://community.pcgamingwiki.com/files/download/109-old-games-widescreen-patch/'

7z e -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/Old_Games_Widescreen_Patch.rar" \
Old_Games_Widescreen_Patch/*
