#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VER=$(python "$NEBULA_DIR/dialogs.py" list "Windows, Linux (+490 Mb)")

if [ "$VER" == "Linux (+490 Mb)" ]; then

LINK_SDL='http://ftp.debian.org/debian/pool/main/libs/libsdl1.2/libsdl1.2debian_1.2.15-10+b1_i386.deb'
LINK_SDL_MIXER='http://ftp.debian.org/debian/pool/main/s/sdl-mixer1.2/libsdl-mixer1.2_1.2.12-11+b1_i386.deb'
LINK_LIBX11='http://ftp.debian.org/debian/pool/main/libx/libx11/libx11-6_1.6.2-3_i386.deb'
LINK_LIBGLU='http://ftp.debian.org/debian/pool/main/libg/libglu/libglu1-mesa_9.0.0-2_i386.deb'
LINK_LIBXCURSOR='http://ftp.debian.org/debian/pool/main/libx/libxcursor/libxcursor1_1.1.14-1+b1_i386.deb'
LINK_LIBOPENAL='http://ftp.debian.org/debian/pool/main/o/openal-soft/libopenal1_1.15.1-5_i386.deb'
LINK_NWMOVIES='https://github.com/nwnlinux/nwmovies/archive/master.zip'
LINK_BINK='http://www.radgametools.com/down/Bink/BinkLinuxPlayer.7z'
LINK_CLIENT129='ftp://ftp.dvo.ru/pub/distfiles/nwclient129.tar.gz'
#LINK_CLIENT129='ftp://ftp.twaren.net/pub/BSD/FreeBSD/ports/distfiles/linux-nwnclient/nwclient129.tar.gz'
LINK_CLIENT169_XP2='ftp://ftp.dvo.ru/pub/distfiles/English_linuxclient169_xp2.tar.gz'
#LINK_CLIENT169_XP2='https://neverwintervault.org/sites/all/modules/pubdlcnt/pubdlcnt.php?file=https://neverwintervault.org/sites/neverwintervault.org/files/english_linuxclient169_xp2.tar_.gz&nid=117'

get_file 'libsdl1.2debian_1.2.15-10+b1_i386.deb' "$LINK_SDL"
get_file 'libsdl-mixer1.2_1.2.12-11+b1_i386.deb' "$LINK_SDL_MIXER"
get_file 'libx11-6_1.6.2-3_i386.deb' "$LINK_LIBX11"
get_file 'libglu1-mesa_9.0.0-2_i386.deb' "$LINK_LIBGLU"
get_file 'libxcursor1_1.1.14-1+b1_i386.deb' "$LINK_LIBXCURSOR"
get_file 'libopenal1_1.15.1-5_i386.deb' "$LINK_LIBOPENAL"
get_file 'nwmovies.zip' "$LINK_NWMOVIES"
get_file 'BinkLinuxPlayer.7z' "$LINK_BINK"
get_file 'nwclient129.tar.gz' "$LINK_CLIENT129"
get_file 'english_linuxclient169_xp2.tar.gz' "$LINK_CLIENT169_XP2"

tar -zxvf "$DOWNLOAD_DIR/_distr/$GAME_NAME/nwclient129.tar.gz" -C \
"$INSTALL_DIR/$GAME_NAME/game" \
& proc_timer $! "Extracting nwclient129.tar.gz"
tar -zxvf "$DOWNLOAD_DIR/_distr/$GAME_NAME/english_linuxclient169_xp2.tar.gz" -C \
"$INSTALL_DIR/$GAME_NAME/game" \
& proc_timer $! "Extracting english_linuxclient169_xp2.tar.gz"

mv "$INSTALL_DIR/$GAME_NAME/game/lib" "$INSTALL_DIR/$GAME_NAME/game/lib.bak"
mkdir "$INSTALL_DIR/$GAME_NAME/game/lib"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libglu1-mesa_9.0.0-2_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libGLU.so.1" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libGLU.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libopenal1_1.15.1-5_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libopenal.so.1" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libopenal.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libsdl1.2debian_1.2.15-10+b1_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libSDL-1.2.so.0.11.4" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libSDL-1.2.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libsdl-mixer1.2_1.2.12-11+b1_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libSDL_mixer-1.2.so.0" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libSDL_mixer-1.2.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libx11-6_1.6.2-3_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libX11.so.6.3.0" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libX11.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/libxcursor1_1.1.14-1+b1_i386.deb" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
7z x -aoa "$INSTALL_DIR/$GAME_NAME/game/tmp/data.tar" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
mv "$INSTALL_DIR/$GAME_NAME/game/tmp/usr/lib/i386-linux-gnu/libXcursor.so.1.0.2" \
"$INSTALL_DIR/$GAME_NAME/game/lib/libXcursor.so"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/nwmovies.zip" \
-o"$INSTALL_DIR/$GAME_NAME/game/tmp"
tar -zxvf "$INSTALL_DIR/$GAME_NAME/game/tmp/nwmovies-master/nwmovies-v4-public.20090223.080954.tar.gz" -C \
"$INSTALL_DIR/$GAME_NAME/game/"

7z x -aoa "$DOWNLOAD_DIR/_distr/$GAME_NAME/BinkLinuxPlayer.7z" "BinkPlayer" \
-o"$INSTALL_DIR/$GAME_NAME/game/nwmovies"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/nwmovies/BinkPlayer"

echo "[Display Options]
AllowWindowedMode=1
FullScreen=0" > "$INSTALL_DIR/$GAME_NAME/game/nwn.ini"

echo '#!/bin/sh
GAME_DIR="$INSTALL_DIR/'"$GAME_NAME"'/game"
export SDL_MOUSE_RELATIVE=0
export SDL_VIDEO_X11_DGAMOUSE=0
export __GL_FSAA_MODE=4
export LD_PRELOAD="$GAME_DIR/nwmovies.so"
export LD_LIBRARY_PATH="$GAME_DIR/lib:$GAME_DIR/miles:$LD_LIBRARY_PATH"
cd "$GAME_DIR"
if [ ! -f "$GAME_DIR/.nwmovies" ]; then
touch "$GAME_DIR/.nwmovies"
./nwmain $@
./nwmain $@
else
./nwmain $@
fi' > "$START_GN_FILE" && chmod +x "$START_GN_FILE"

echo '#!/bin/sh
python "$NEBULA_DIR/launcher_native.py" '"$GAME_NAME" > "$START_FILE"

rm "$SETTINGS_FILE" "$ADDITIONS_FILE"

fi
