#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/sanitarium/tmp/app' $INSTALL_DIR'/sanitarium/game'
rm -R -f $INSTALL_DIR'/sanitarium/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py sanitarium sntrm.exe' > \
$INSTALL_DIR'/sanitarium/start.sh'
chmod +x $INSTALL_DIR'/sanitarium/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/sanitarium
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/sanitarium/game \
$WINEPREFIX_DIR/drive_c/Games/sanitarium' > \
$INSTALL_DIR'/sanitarium/additions.sh'
chmod +x $INSTALL_DIR'/sanitarium/additions.sh'
