#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/prince_of_persia/tmp/app' $INSTALL_DIR'/prince_of_persia/game'
rm -R -f $INSTALL_DIR'/prince_of_persia/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' -C - \
	'http://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE'
fi

mkdir -p $HOME'/.cache/winetricks/vcrun2005'
if [ ! -f $HOME'/.cache/winetricks/vcrun2005/vcredist_x86.EXE' ]; then
	cp $DOWNLOAD_DIR'/_distr/vcredist_x86.EXE' $HOME'/.cache/winetricks/vcrun2005/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py prince_of_persia PrinceOfPersia_Launcher.exe' > \
$INSTALL_DIR'/prince_of_persia/start.sh'
chmod +x $INSTALL_DIR'/prince_of_persia/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/prince_of_persia/game/Launcher
$WINELOADER Launcher.exe' > $INSTALL_DIR'/prince_of_persia/settings.sh'
chmod +x $INSTALL_DIR'/prince_of_persia/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia" /v \
"Executable" /t REG_SZ /d $INSTALL_DIR_WIN\\\\prince_of_persia\\\\game\\\\PrinceOfPersia_Launcher.exe /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia" /v \
"InstallDir" /t REG_SZ /d $INSTALL_DIR_WIN\\\\prince_of_persia\\\\game /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia" /v \
"Language" /t REG_SZ /d "English" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia" /v \
"installdir" /t REG_SZ /d $INSTALL_DIR_WIN\\\\prince_of_persia\\\\game /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia" /v \
"language" /t REG_SZ /d "us" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia\GameUpdate" /v \
"execPath" /t REG_SZ /d $INSTALL_DIR_WIN"\\\\prince_of_persia\\\\game\\\\Prince of Persia.exe" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\\Ubisoft\Prince of Persia\GameUpdate" /v \
"info" /t REG_SZ /d "08a0f1c01d540ee143f7ee48a91898fa" /f

winetricks --gui vcrun2005

rm $WINEPREFIX_DIR/drive_c/Games/prince_of_persia
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/prince_of_persia/game \
$WINEPREFIX_DIR/drive_c/Games/prince_of_persia' > $INSTALL_DIR'/prince_of_persia/additions.sh'
chmod +x $INSTALL_DIR'/prince_of_persia/additions.sh'
