#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/the_witcher/tmp/app' $INSTALL_DIR'/the_witcher/game'
rm -R -f $INSTALL_DIR'/the_witcher/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py the_witcher launcher.exe' > \
$INSTALL_DIR'/the_witcher/start.sh'
chmod +x $INSTALL_DIR'/the_witcher/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\CD Projekt Red\The Witcher" \
/v "InstallFolder" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_witcher\\\\game /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\CD Projekt Red\The Witcher" \
/v "IsDjinniInstalled" /t REG_DWORD /d "1" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\CD Projekt Red\The Witcher" \
/v "Language" /t REG_SZ /d "3" /f
$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\CD Projekt Red\The Witcher" \
/v "RegionVersion" /t REG_SZ /d "US" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\Wine\Direct3D" /v \
"CheckFloatConstants" /t REG_SZ /d "enabled" /f

winetricks --gui d3dx9

rm $WINEPREFIX_DIR/drive_c/Games/the_witcher
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/the_witcher/game \
$WINEPREFIX_DIR/drive_c/Games/the_witcher' > \
$INSTALL_DIR'/the_witcher/additions.sh'
chmod +x $INSTALL_DIR'/the_witcher/additions.sh'
