#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/shadowrun_returns/tmp/data/noarch/'* $INSTALL_DIR'/shadowrun_returns/'
rm -R -f $INSTALL_DIR'/shadowrun_returns/tmp'
mv $INSTALL_DIR'/shadowrun_returns/start.sh' $INSTALL_DIR'/shadowrun_returns/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./Shadowrun"' > $INSTALL_DIR'/shadowrun_returns/start_gn.sh'
chmod +x $INSTALL_DIR'/shadowrun_returns/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py shadowrun_returns' > \
$INSTALL_DIR'/shadowrun_returns/start.sh'
chmod +x $INSTALL_DIR'/shadowrun_returns/start.sh'
