#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'alone_in_the_dark_1' \
'https://images-4.gog.com/cc3623efccf2d4be01bb3364b23bb8710a4bdc323710ef72af6d7c1d72077b6c.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/alone_in_the_dark_1/tmp/app' $INSTALL_DIR'/alone_in_the_dark_1/game'
rm -R -f $INSTALL_DIR'/alone_in_the_dark_1/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/alone_in_the_dark_1/game \
$HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1
python $NEBULA_DIR/launcher_dosbox.py alone_in_the_dark_1' > \
$INSTALL_DIR'/alone_in_the_dark_1/start.sh'
chmod +x $INSTALL_DIR'/alone_in_the_dark_1/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1
imgmount d $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1/GAME.INST -fs iso
c:
cls

echo.
echo.
ECHO  --------------------------------- 
ECHO  Alone in the Dark                 
ECHO  --------------------------------- 
ECHO  1) Alone in the Dark             
ECHO  2) Jack in the Dark              
ECHO  --------------------------------- 
ECHO  3) exit program                  
ECHO  --------------------------------- 
echo.
echo.

choice /c123 /s Which game do you want to run? [1-3]: /n 
if errorlevel 3 goto exit
if errorlevel 2 goto jack
if errorlevel 1 goto alone

:alone
cls
CD INDARK
INDARK
exit

:jack
cls
CD JACK
indark2 16 1
cleardrv >NUL
exit

:exit
exit" > $INSTALL_DIR'/alone_in_the_dark_1/dosbox_game.conf'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1
imgmount d $HOME/.games_nebula/games/.dosbox/alone_in_the_dark_1/GAME.INST -fs iso
c:
cls

ECHO [1;33m[42mЙННННННННННННННННННННННННННННННННННН»
ECHO є --------------------------------- є
ECHO є Game Settings (inc. language)     є
ECHO є --------------------------------- є
ECHO є  1) Alone in the Dark             є
ECHO є  2) Jack in the Dark              є
ECHO є --------------------------------- є
ECHO є  3) exit program                  є
ECHO є --------------------------------- є
ECHO ИНННННННННННННННННННННННННННННННННННј[0m

choice /c123 /s Which program do you want to run? [1-3]: /n 
if errorlevel 3 goto exit
if errorlevel 2 goto jack
if errorlevel 1 goto alone

:alone
cls
CD INDARK
INSTALL
exit

:jack
cls
CD JACK
INSTALL
exit

:exit
exit" > $INSTALL_DIR'/alone_in_the_dark_1/dosbox_settings.conf'
