#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/stacking/tmp/data/noarch/'* $INSTALL_DIR'/stacking/'
rm -R -f $INSTALL_DIR'/stacking/tmp'
mv $INSTALL_DIR'/stacking/start.sh' $INSTALL_DIR'/stacking/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./Stack.bin.x86"' > $INSTALL_DIR'/stacking/start_gn.sh'
chmod +x $INSTALL_DIR'/stacking/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py stacking' > \
$INSTALL_DIR'/stacking/start.sh'
chmod +x $INSTALL_DIR'/stacking/start.sh'
