#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/trine_enchanted_edition/tmp/data/noarch/'* $INSTALL_DIR'/trine_enchanted_edition/'
rm -R -f $INSTALL_DIR'/trine_enchanted_edition/tmp'
mv $INSTALL_DIR'/trine_enchanted_edition/start.sh' $INSTALL_DIR'/trine_enchanted_edition/start_gog.sh'


echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ ! -d "$HOME/.frozenbyte/Trine1" ]; then
    mkdir -p "$HOME/.frozenbyte/Trine1"
fi
if [ ! -f "$HOME/.frozenbyte/Trine1/install_dir.txt" ]; then
    echo "GAME_INSTALL_DIR=$DIR/game" > "$HOME/.frozenbyte/Trine1/install_dir.txt"
fi
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./bin/trine1_linux_launcher_32bit"' > $INSTALL_DIR'/trine_enchanted_edition/start_gn.sh'
chmod +x $INSTALL_DIR'/trine_enchanted_edition/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py trine_enchanted_edition' > \
$INSTALL_DIR'/trine_enchanted_edition/start.sh'
chmod +x $INSTALL_DIR'/trine_enchanted_edition/start.sh'

