#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_common_file 'iv5setup.exe' \
'http://s3.amazonaws.com/moviecodec/files/iv5setup.exe'

echo -e 'mkdir -p "$WINEPREFIX/drive_c/windows/system32"
7z x -o"/tmp/iv5setup" "$DOWNLOAD_DIR/_distr/iv5setup.exe"
cd "/tmp/iv5setup"
unshield x data1.cab
cp Indeo_3_2_codec/ir32_32.dll "$WINEPREFIX/drive_c/windows/system32"
rm -R "/tmp/iv5setup"
"$WINELOADER" reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\drivers.desc" \
/v "ir32_32.dll" /t REG_SZ /d "Indeo® Video R3.2" /f
"$WINELOADER" reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Drivers32" \
/v "vidc.iv32" /t REG_SZ /d "ir32_32.dll" /f' >> "$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"

cd "$INSTALL_DIR/$GAME_NAME/game/data/intro/"
ffmpeg -i intro.avi -vcodec copy -acodec adpcm_ima_wav new_intro.avi  > /dev/null 2>&1 \
& proc_timer $! "Converting intro.avi"
mv new_intro.avi intro.avi
echo "Done"
