#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_common_file 'LAVFilters-0.69-x86.zip' \
'https://github.com/Nevcairiel/LAVFilters/releases/download/0.69/LAVFilters-0.69-x86.zip'

echo -e 'mkdir -p "$WINEPREFIX/drive_c/Program Files/LAVFilters"
7z x -aoa -o"$WINEPREFIX/drive_c/Program Files/LAVFilters" \
"$DOWNLOAD_DIR/_distr/LAVFilters-0.69-x86.zip"
cd "$WINEPREFIX/drive_c/Program Files/LAVFilters"
"$WINELOADER" regsvr32.exe LAVSplitter.ax
"$WINELOADER" regsvr32.exe LAVVideo.ax
"$WINELOADER" regsvr32.exe LAVAudio.ax' > \
"$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"

cd "$INSTALL_DIR/$GAME_NAME/game/video/"
ffmpeg -i "intro.mpg" -i "intro.mp2" -codec copy "new_intro.mpg" \
& proc_timer $! "Converting intro.mpg"
mv "new_intro.mpg" "intro.mpg"
ffmpeg -i "outro1.mpg" -vf scale=640:480 -q 1 "new_outro1.mpg" \
& proc_timer $! "Converting outro1.mpg"
mv "new_outro1.mpg" "outro1.mpg"
ffmpeg -i "outro5.mpg" -i "outro5.mp2" -codec copy "new_outro5.mpg" \
& proc_timer $! "Converting outro5.mpg"
mv "new_outro5.mpg" "outro5.mpg"
ffmpeg -i "trans.mpg" -i "trans.mp2" -codec copy "new_trans.mpg" \
& proc_timer $! "Converting outro5.mpg"
mv "new_trans.mpg" "trans.mpg"
rm "intro.mp2" "outro5.mp2" "trans.mp2"
