#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/bloodrayne/tmp/app' $INSTALL_DIR'/bloodrayne/game'
rm -R -f $INSTALL_DIR'/bloodrayne/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/LAVFilters-0.68.1-x86.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/LAVFilters-0.68.1-x86.zip'  -C - \
	'https://github.com/Nevcairiel/LAVFilters/releases/download/0.68.1/LAVFilters-0.68.1-x86.zip'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/LAVFilters-0.68.1-x64.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/LAVFilters-0.68.1-x64.zip'  -C - \
	'https://github.com/Nevcairiel/LAVFilters/releases/download/0.68.1/LAVFilters-0.68.1-x64.zip'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

cd $INSTALL_DIR'/bloodrayne/game/video/'
ffmpeg -i 'intro.mpg' -i 'intro.mp2' -codec copy 'new_intro.mpg'
mv 'new_intro.mpg' 'intro.mpg'
ffmpeg -i 'outro5.mpg' -i 'outro5.mp2' -codec copy 'new_outro5.mpg'
mv 'new_outro5.mpg' 'outro5.mpg'
ffmpeg -i 'trans.mpg' -i 'trans.mp2' -codec copy 'new_trans.mpg'
mv 'new_trans.mpg' 'trans.mpg'
rm 'intro.mp2' 'outro5.mp2' 'trans.mp2'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py bloodrayne rayne.exe' > \
$INSTALL_DIR'/bloodrayne/start.sh'
chmod +x $INSTALL_DIR'/bloodrayne/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
DOWNLOAD_DIR=$4

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

mkdir -p $WINEPREFIX"/drive_c/Program Files/LAVFilters"

if [ -d $WINEPREFIX/drive_c/windows/syswow64 ]; then
	unzip -o $DOWNLOAD_DIR/_distr/LAVFilters-0.68.1-x64.zip -d \
	$WINEPREFIX"/drive_c/Program Files/LAVFilters"
else
	unzip -o $DOWNLOAD_DIR/_distr/LAVFilters-0.68.1-x86.zip -d \
	$WINEPREFIX"/drive_c/Program Files/LAVFilters"
fi

cd $WINEPREFIX"/drive_c/Program Files/LAVFilters"
$WINELOADER regsvr32.exe LAVSplitter.ax
$WINELOADER regsvr32.exe LAVVideo.ax
$WINELOADER regsvr32.exe LAVAudio.ax

winetricks --gui quartz devenum

rm $WINEPREFIX_DIR/drive_c/Games/bloodrayne
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/bloodrayne/game \
$WINEPREFIX_DIR/drive_c/Games/bloodrayne' > \
$INSTALL_DIR'/bloodrayne/additions.sh'
chmod +x $INSTALL_DIR'/bloodrayne/additions.sh'
