#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"
heroes_chronicles_counter "add"

echo -e '#!/bin/bash
source "$NEBULA_DIR/scripts/shell_functions.sh"
heroes_chronicles_update_links' > \
"$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"
