#!/bin/bash

echo -e '
AF_DOWNLOAD_DIR="$DOWNLOAD_DIR/$GAME_NAME/dlc/eador_masters_of_the_broken_world_allied_forces"
AF_DIR="$INSTALL_DIR/$GAME_NAME/game/eador_masters_of_the_broken_world_allied_forces"

install_af_dlc () {
INSTALLER=$(ls "$AF_DIR")
"$WINELOADER" "$AF_DIR/$INSTALLER" /VERYSILENT /SUPPRESSMSGBOXES \
/DIR=C:\\\\Games\\\\eador_masters_of_the_broken_world
}

if [ -d "$AF_DIR" ]; then
install_af_dlc
else
if [ -d "$AF_DOWNLOAD_DIR" ]; then
cp -r "$AF_DOWNLOAD_DIR" "$INSTALL_DIR/$GAME_NAME/game/"
install_af_dlc
fi
fi' >> "$ADDITIONS_FILE" && chmod +x "$ADDITIONS_FILE"
