#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/eador_masters_of_the_broken_world/tmp/app' \
$INSTALL_DIR'/eador_masters_of_the_broken_world/game'
rm -R -f $INSTALL_DIR'/eador_masters_of_the_broken_world/tmp'

$INSTALL_DIR'/eador_masters_of_the_broken_world/game/__support/save/'* \
$INSTALL_DIR'/eador_masters_of_the_broken_world/game/'

# Move out broken updater
mv $INSTALL_DIR'/eador_masters_of_the_broken_world/game/update.exe' \
$INSTALL_DIR'/eador_masters_of_the_broken_world/game/update.exe.bak'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe'  -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/scripten.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/scripten.exe'  -C - \
	'http://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/MPSetup.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/MPSetup.exe'  -C - \
	'http://download.microsoft.com/download/1/b/c/1bc0b1a3-c839-4b36-8f3c-19847ba09299/MPSetup.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe'  -C - \
	'http://birds.camden.rutgers.edu/WM9Codecs9x.exe'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

mkdir -p $HOME'/.cache/winetricks/wsh57'
if [ ! -f $HOME'/.cache/winetricks/wsh57/scripten.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/scripten.exe' $HOME'/.cache/winetricks/wsh57/'
fi

mkdir -p $HOME'/.cache/winetricks/wmp9'
if [ ! -f $HOME'/.cache/winetricks/wmp9/MPSetup.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/MPSetup.exe' $HOME'/.cache/winetricks/wmp9/'
fi

mkdir -p $HOME'/.cache/winetricks/wm9codecs'
if [ ! -f $HOME'/.cache/winetricks/wm9codecs/WM9Codecs9x.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/WM9Codecs9x.exe' $HOME'/.cache/winetricks/wm9codecs/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py eador_masters_of_the_broken_world eador_mbw.exe' > \
$INSTALL_DIR'/eador_masters_of_the_broken_world/start.sh'
chmod +x $INSTALL_DIR'/eador_masters_of_the_broken_world/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/eador_masters_of_the_broken_world/game
$WINELOADER config.exe' > $INSTALL_DIR'/eador_masters_of_the_broken_world/settings.sh'
chmod +x $INSTALL_DIR'/eador_masters_of_the_broken_world/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
DOWNLOAD_DIR=$4
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_LOCAL_MACHINE\Software\GOG.com\Games\1207659194" /v \
"PATH" /t REG_SZ /d $INSTALL_DIR_WIN\\\\eador_masters_of_the_broken_world\\\\game /f

AF_DLC=$DOWNLOAD_DIR/eador_masters_of_the_broken_world/dlc/eador_masters_of_the_broken_world_allied_forces
if [ -e $AF_DLC ]; then
	cd $AF_DLC
	DLC_INSTALLER=$(ls)
	cp $DLC_INSTALLER $INSTALL_DIR/eador_masters_of_the_broken_world/
	cd $INSTALL_DIR/eador_masters_of_the_broken_world
	$WINELOADER $DLC_INSTALLER /VERYSILENT /SUPPRESSMSGBOXES \
	/DIR=$INSTALL_DIR_WIN"\\eador_masters_of_the_broken_world\game"
	rm $DLC_INSTALLER
fi
winetricks --gui quartz devenum wmp9

rm $WINEPREFIX_DIR/drive_c/Games/eador_masters_of_the_broken_world
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/eador_masters_of_the_broken_world/game \
$WINEPREFIX_DIR/drive_c/Games/eador_masters_of_the_broken_world' > \
$INSTALL_DIR'/eador_masters_of_the_broken_world/additions.sh'
chmod +x $INSTALL_DIR'/eador_masters_of_the_broken_world/additions.sh'
