#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'tropico_2' \
'https://images-3.gog.com/9f932d349c0c41c0fdde813f54220a6d2da74471e6287c7570e9e5cf42b39a01.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/tropico_2/tmp/app' $INSTALL_DIR'/tropico_2/game'
rm -R -f $INSTALL_DIR'/tropico_2/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py tropico_2 Tropico2.exe' > \
$INSTALL_DIR'/tropico_2/start.sh'
chmod +x $INSTALL_DIR'/tropico_2/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/tropico_2
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/tropico_2/game \
$WINEPREFIX_DIR/drive_c/Games/tropico_2' > \
$INSTALL_DIR'/tropico_2/additions.sh'
chmod +x $INSTALL_DIR'/tropico_2/additions.sh'
