#!/bin/bash
echo "[autoexec]
@echo off
mount c $HOME/.games_nebula/games/.dosbox/$GAME_NAME
c:
cls

echo.
echo.
ECHO  ---------------------------------
ECHO  Tyrian 2000
ECHO  ---------------------------------
ECHO  1) Tyrian 2000
ECHO  2) Tyrian 2000 Editor
ECHO  ---------------------------------
ECHO  3) Exit program
ECHO  ---------------------------------
echo.
echo.

choice /c123 /s Which application do you want to run? [1-3]: /n
if errorlevel 3 goto exit
if errorlevel 2 goto editor
if errorlevel 1 goto game

:game
cls
tyrian.exe
exit

:editor
cls
SHIPEDIT.EXE
exit

:exit
exit" > "$DOSBOX_GAME_CONF"
