#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

lgogdownloader --download --game "$GAME_NAME" --platform 4 --exclude 4,16 \
--ignore-dlc-count  --directory="$DOWNLOAD_DIR"

7z x -aoa  -o"$INSTALL_DIR/$GAME_NAME" "$DOWNLOAD_DIR/$GAME_NAME/extras/hlm_2_comics_linux.zip" \
& proc_timer $! "Extracting hlm_2_comics_linux.zip"

mv "$INSTALL_DIR/$GAME_NAME/hlm_2_comics_linux/"* "$INSTALL_DIR/$GAME_NAME/"

chmod +x "$INSTALL_DIR/$GAME_NAME/linux32/hlm2comics"
chmod +x "$INSTALL_DIR/$GAME_NAME/linux64/hlm2comics"

rm -R "$INSTALL_DIR/$GAME_NAME/hlm_2_comics_linux"

ARCH=$(get_arch x)
if [ "$ARCH" == "x86_64" ]; then
echo -e '#!/bin/bash
"$INSTALL_DIR/'"$GAME_NAME"'/linux64/hlm2comics"' > \
"$START_GN_FILE" && chmod +x "$START_GN_FILE"
else
echo -e '#!/bin/bash
"$INSTALL_DIR/'"$GAME_NAME"'/linux32/hlm2comics"' > \
"$START_GN_FILE" && chmod +x "$START_GN_FILE"
fi

echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_native.py" '"$GAME_NAME" > \
"$START_FILE" && chmod +x "$START_FILE"
