#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/edna_harvey_harveys_new_eyes/tmp/data/noarch/'* \
$INSTALL_DIR'/edna_harvey_harveys_new_eyes/'
rm -R -f $INSTALL_DIR'/edna_harvey_harveys_new_eyes/tmp'
mv $INSTALL_DIR'/edna_harvey_harveys_new_eyes/start.sh' \
$INSTALL_DIR'/edna_harvey_harveys_new_eyes/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/libs64"
cd "$DIR/game"
"./harvey"' > $INSTALL_DIR'/edna_harvey_harveys_new_eyes/start_gn.sh'
chmod +x $INSTALL_DIR'/edna_harvey_harveys_new_eyes/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py edna_harvey_harveys_new_eyes' > \
$INSTALL_DIR'/edna_harvey_harveys_new_eyes/start.sh'
chmod +x $INSTALL_DIR'/edna_harvey_harveys_new_eyes/start.sh'
