#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/spelunky/tmp/app' $INSTALL_DIR'/spelunky/game'
rm -R -f $INSTALL_DIR'/spelunky/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py spelunky Spelunky.exe' > \
$INSTALL_DIR'/spelunky/start.sh'
chmod +x $INSTALL_DIR'/spelunky/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/spelunky
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/spelunky/game \
$WINEPREFIX_DIR/drive_c/Games/spelunky' > \
$INSTALL_DIR'/spelunky/additions.sh'
chmod +x $INSTALL_DIR'/spelunky/additions.sh'
