#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VER=$(python "$NEBULA_DIR/dialogs.py" list "Windows, DOS (+0.5 Mb)")

if [ "$VER" == "DOS (+0.5 Mb)" ]; then

get_file 'dos_binaries.zip' \
'http://www.sierrahelp.com/forums/download/file.php?id=3748&sid=3b766caff456bb3911775dae8ca201ad'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/dos_binaries.zip" \
& proc_timer $! "Extracting dos_binaries.zip"

echo '#!/bin/bash
python "$NEBULA_DIR/launcher_dosbox.py" '"$GAME_NAME" > "$START_FILE"

echo "[autoexec]
@echo off
mount c $HOME/.games_nebula/games/.dosbox/$GAME_NAME
c:
cls
sier.exe
cls
exit" > "$DOSBOX_GAME_CONF"

### Trailing spaces important! ###
echo "videoDrv   = VESA.DRV
soundDrv   = MIDNONE.DRV
audioDrv   = DACBLAST.DRV
joyDrv     = NO
directory  = .\
minCPU     = 486
minDOS     = 572
mode       = real
minEMS     = 200
CD         = yes
CPU        = 0
VideoSpeed = 0
CPUSpeed   = 0
CDROM      = 0
mouseDrv   = NONE
memoryDrv  = NONE
language   = 1
audioSize  = 112k
minMemory  = 1600k
brightness = 0
cmd        = LSL7DOS

audio      = .\music 
resSfx     = .\ 
resAud     = .\ 
resMap     = .\ 
patchDir   = .\; .\patches\ 
movieDir   = .\movie" > \
"$INSTALL_DIR/$GAME_NAME/game/RESOURCE.CFG"

else

echo "[Windows]
borderpixels=0
minSubmits=8
resSfx=C:\Games\\$GAME_NAME
resAud=C:\Games\\$GAME_NAME
leadSubmits=4
maxSubmits=32
winG=false
confirmdac=true
sciMinK=3200
useDirectDraw=false
movieDir=C:\Games\\$GAME_NAME\Movie\\
patchDir=C:\Games\\$GAME_NAME;C:\Games\\$GAME_NAME\PATCHES\\
useaudio=true
wwidth=640
VideoSpeed=300
resMap=C:\Games\\$GAME_NAME
sciMaxK=5400
usemidi=false
wheight=480
allowresize=false
cacheSize2=750
useDirectSound=false
audio=C:\Games\\$GAME_NAME\Music\\
cacheSize3=350
title=Leisure Suit Larry in 'Love For Sail!'" > \
"$INSTALL_DIR/$GAME_NAME/game/RESOURCE.WIN"

fi
