#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_common_file 'WeiDU-Linux-240.zip' \
'http://www.weidu.org/%7Ethebigg/WeiDU-Linux-240.zip'

7z e -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/WeiDU-Linux-240.zip" \
"WeiDU-Linux/bin/i386/weidu" \
"WeiDU-Linux/bin/i386/tolower" \

get_common_file 'lin-widescreen-v3.07.tar.gz' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=869'

get_file 'lin-bg2fixpack-v10.tar.gz' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=742'

get_file 'UnfinishedBusiness-v26.zip' \
'http://mods.pocketplane.net/UnfinishedBusiness-v26.zip'

get_file 'lin-bg2_tweaks-v16.tar.gz' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=743'

get_file 'BGT118-Install.rar' \
'http://www.shsforums.net/files/download/54-baldurs-gate-trilogy-weidu/'

get_file 'BG2-Bigger-Fonts.rar' \
'http://www.shsforums.net/index.php?app=core&module=attach&section=attach&attach_id=23681'

get_file 'bg1ub-v14.zip' \
'http://mods.pocketplane.net/bg1ubfiles/bg1ub-v14.zip'

mkdir -p "$DOWNLOAD_DIR/_distr/baldurs_gate_the_original_saga"
if [ ! -f "$DOWNLOAD_DIR/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip" ]; then
curl -L -o "$DOWNLOAD_DIR/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip" -C - \
'http://mods.pocketplane.net/bg1ubfiles/bg1ub-v14.zip'
fi

tar -xzvf "$DOWNLOAD_DIR/_distr/lin-widescreen-v3.07.tar.gz" -C "$INSTALL_DIR/$GAME_NAME/game"

tar -xzvf "$DOWNLOAD_DIR/_distr/$GAME_NAME/lin-bg2fixpack-v10.tar.gz" \
-C "$INSTALL_DIR/$GAME_NAME/game"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/UnfinishedBusiness-v26.zip"

tar -xzvf "$DOWNLOAD_DIR/_distr/$GAME_NAME/lin-bg2_tweaks-v16.tar.gz" \
-C "$INSTALL_DIR/$GAME_NAME/game"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/BGT118-Install.rar"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/bgt/install/unix/x86/"*
cp "$INSTALL_DIR/$GAME_NAME/game/bgt/install/unix/x86/"* \
"$INSTALL_DIR/$GAME_NAME/game/"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/BG2-Bigger-Fonts.rar"

echo "[Alias]
HD0:=C:\Games\\$GAME_NAME
CD1:=C:\Games\\$GAME_NAME\data
CD2:=C:\Games\\$GAME_NAME\data
CD3:=C:\Games\\$GAME_NAME\data
CD4:=C:\Games\\$GAME_NAME\data
CD5:=C:\Games\\$GAME_NAME\data
CD6:=C:\Games\\$GAME_NAME\data
[Program Options]
3D Acceleration=1" > "$INSTALL_DIR/$GAME_NAME/game/baldur.ini"

echo "CD1:=$INSTALL_DIR/$GAME_NAME/game
CD1:=$INSTALL_DIR/$GAME_NAME/game/data
CD1:=$INSTALL_DIR/$GAME_NAME/game/data
CD1:=$INSTALL_DIR/$GAME_NAME/game/data
CD1:=$INSTALL_DIR/$GAME_NAME/game/data
CD1:=$INSTALL_DIR/$GAME_NAME/game/data
CD1:=$INSTALL_DIR/$GAME_NAME/game/data" > \
"$INSTALL_DIR/$GAME_NAME/game/linux.ini"

cd "$INSTALL_DIR/$GAME_NAME/game"
printf 'y\nn\n' | ./tolower

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./widescreen/widescreen.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/widescreen.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/widescreen.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./bg2fixpack/setup-bg2fixpack.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/fixpack.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/fixpack.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./ub/setup-ub.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/ub.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/ub.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./bg2_tweaks/setup-bg2_tweaks.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/tweakpack.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/tweakpack.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./setup-bgt.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/trilogy.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/trilogy.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./bg1ub/setup-bg1ub.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/bg1ub.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/bg1ub.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./setup-bg2-bigger-fonts.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/bigger_fonts.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/bigger_fonts.sh"
