#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/saints_row_gat_out_of_hell/tmp/app' \
$INSTALL_DIR'/saints_row_gat_out_of_hell/game'
rm -R -f $INSTALL_DIR'/saints_row_gat_out_of_hell/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py saints_row_gat_out_of_hell "Saints Row Gat Out of Hell.exe"' > \
$INSTALL_DIR'/saints_row_gat_out_of_hell/start.sh'
chmod +x $INSTALL_DIR'/saints_row_gat_out_of_hell/start.sh'
