#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/inquisitor/tmp/app/GameData' $INSTALL_DIR'/inquisitor/game'
rm -R -f $INSTALL_DIR'/inquisitor/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py inquisitor Inquisitor.exe' > \
$INSTALL_DIR'/inquisitor/start.sh'
chmod +x $INSTALL_DIR'/inquisitor/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/inquisitor
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/inquisitor/game \
$WINEPREFIX_DIR/drive_c/Games/inquisitor' > \
$INSTALL_DIR'/inquisitor/additions.sh'
chmod +x $INSTALL_DIR'/inquisitor/additions.sh'
