#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_from_mega 'pop1_widescreen.7z' \
'https://mega.nz/#!jdoh3Aab!Q0V4trWEZ_vxmsAfslx_Yrtmp81BuLm1RewH3LoqG1c'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/pop1_widescreen.7z" \
'pop.7z'

7z x -aoa -p'pop' -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$INSTALL_DIR/$GAME_NAME/game/pop.7z"
