#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 "$NEBULA_DIR/modules/goglib_get_banner_2.py" \
'commandos_behind_enemy_lines' \
'https://images-2.gog.com/769bc477a07e42d57a24eb9c127c222c142fbd7fe5839559e389a03e6cbde870.jpg' \
"$HOME/.games_nebula/images/goglib_banners"

mv "$INSTALL_DIR/commandos_behind_enemy_lines/tmp/app" \
"$INSTALL_DIR/commandos_behind_enemy_lines/game"
rm -R -f "$INSTALL_DIR/commandos_behind_enemy_lines/tmp"

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py commandos_behind_enemy_lines comandos.exe' > \
"$INSTALL_DIR/commandos_behind_enemy_lines/start.sh"
chmod +x "$INSTALL_DIR/commandos_behind_enemy_lines/start.sh"
