#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'heroes_chronicles_chapter_7_revolt_of_the_beastmasters' \
'https://images-1.gog.com/a798c65f61da6825fb84ac3321bca11295fb267cc528886cccca92b1432239f5.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/tmp/app' \
$INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/game'
rm -R -f $INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/tmp'

mkdir -p $INSTALL_DIR'/heroes_chronicles_common_data'

count_file=$INSTALL_DIR'/heroes_chronicles_common_data/count_file'

count=0
INST_GAMES=$(ls $INSTALL_DIR)
readarray -t INST_GAMES_ARRAY <<<"$INST_GAMES"

IFS=$'\n';
for i in ${INST_GAMES_ARRAY[@]};
	do 
		if [[ $i == heroes_chronicles_chapter* ]] 
			then count=$(($count + 1))
		fi
done

echo $count > $count_file

cd $INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/game'

if (($count == 1)); then
	mv 'Data' $INSTALL_DIR'/heroes_chronicles_common_data/'
	mv 'MP3' $INSTALL_DIR'/heroes_chronicles_common_data/'
	ln -s $INSTALL_DIR'/heroes_chronicles_common_data/Data' 'Data'
	ln -s $INSTALL_DIR'/heroes_chronicles_common_data/MP3' 'MP3'
else
	rm -R -f 'Data'
	rm -R -f 'MP3'
	ln -s $INSTALL_DIR'/heroes_chronicles_common_data/Data' 'Data'
	ln -s $INSTALL_DIR'/heroes_chronicles_common_data/MP3' 'MP3'
fi

echo -e '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
cd $INSTALL_DIR/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/game/
rm Data
rm MP3
ln -s $INSTALL_DIR/heroes_chronicles_common_data/Data Data
ln -s $INSTALL_DIR/heroes_chronicles_common_data/MP3 MP3
python $NEBULA_DIR/launcher_wine.py heroes_chronicles_chapter_7_revolt_of_the_beastmasters "Revolt of the Beastmasters/Beastmaster.exe"' > \
$INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/start.sh'
chmod +x $INSTALL_DIR'/heroes_chronicles_chapter_7_revolt_of_the_beastmasters/start.sh'
