#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/the_longest_journey/tmp/app' $INSTALL_DIR'/the_longest_journey/game'
rm -R -f $INSTALL_DIR'/the_longest_journey/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py the_longest_journey game.exe' > \
$INSTALL_DIR'/the_longest_journey/start.sh'
chmod +x $INSTALL_DIR'/the_longest_journey/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Fmv" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Global" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\Global\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\\\\Roots" /v \
"Levels" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Program" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Root" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Sound" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\ /f
$WINELOADER reg add "HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Paper Sun\Roots" /v \
"Static" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_longest_journey\\\\game\\\\Static\\\\ /f

rm $WINEPREFIX_DIR/drive_c/Games/the_longest_journey
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/the_longest_journey/game \
$WINEPREFIX_DIR/drive_c/Games/the_longest_journey' > \
$INSTALL_DIR'/the_longest_journey/additions.sh'
chmod +x $INSTALL_DIR'/the_longest_journey/additions.sh'
