#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_from_mega 'bge_widescreen.7z' \
'https://mega.nz/#!yZRQyAAD!slkCYrNFbKw1RfNlY1LPVyir9axaPoToHENbSSDzsQ8'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/bge_widescreen.7z" \
'bge.7z'

7z x -aoa -p'bge' -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$INSTALL_DIR/$GAME_NAME/game/bge.7z"
