#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'leisure_suit_larry_2_looking_for_love_in_several_wrong_places' \
'https://images-4.gog.com/7b0c8360eacbffa6a5a8380a15abb5d3f26d8a237c03691aadf332b287ff14ee.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/tmp/data/noarch/data' \
$INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/game'
rm -R -f $INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/tmp'

echo -e '#!/bin/bash

INSTALL_DIR=$1
NEBULA_DIR=$2

SCUMMVMRC=$INSTALL_DIR/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/scummvmrc
readarray -t ARRAY <<<"$(cat "$SCUMMVMRC")"
LENGHT=${#ARRAY[@]}

for i in $(seq 1 $LENGHT); do
	if [[ ${ARRAY[i]} == "[lsl2]" ]]; then
		FIRST_LINE=$i
	fi
done

cp $HOME/.games_nebula/config/scummvmrc $SCUMMVMRC

for i in $(seq $FIRST_LINE $LENGHT); do 
	echo ${ARRAY[i]} >> "$SCUMMVMRC"
done

python $NEBULA_DIR/launcher_scummvm.py leisure_suit_larry_2_looking_for_love_in_several_wrong_places lsl2' > \
$INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/start.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/start.sh'

cp $HOME'/.games_nebula/config/scummvmrc' \
$INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/'

echo "[lsl2]
description=Leisure Suit Larry 2: Goes Looking for Love (in Several Wrong Places) (DOS/English)
gameid=sci
path=$INSTALL_DIR/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/game
savepath=$INSTALL_DIR/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/game" >> \
$INSTALL_DIR'/leisure_suit_larry_2_looking_for_love_in_several_wrong_places/scummvmrc'
