#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

ARCH=$(get_arch x)
if [ "$ARCH" == "x86_64" ]; then
get_java_x64
else
get_java_i586
fi

get_common_file \
'lwjgl-2.7.1.zip' \
'http://downloads.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%202.7.1/lwjgl-2.7.1.zip'
mkdir -p "$INSTALL_DIR/$GAME_NAME/lib"
7z e -aoa -o"$INSTALL_DIR/$GAME_NAME/lib" "$DOWNLOAD_DIR/_distr/lwjgl-2.7.1.zip" \
lwjgl-2.7.1/native/linux/*

echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_native.py" '"$GAME_NAME" > \
"$START_FILE" && chmod +x "$START_FILE"

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export JAVA_HOME="$DIR/game"
cd "$DIR/game"
../jre/bin/java  "-Duser.home=saves" \
"-Djava.library.path=../lib" \
-noverify -jar Edna.jar' > \
"$START_GN_FILE" && chmod +x "$START_GN_FILE"
