#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2
WINE_PATH=$4

mv $INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp/game' \
$INSTALL_DIR'/vampire_the_masquerade_bloodlines/game'
rm -R -f $INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
export WINEDLLOVERRIDES="dbghelp=n,b"
python $NEBULA_DIR/launcher_wine.py vampire_the_masquerade_bloodlines "vampire.exe -game Unofficial_Patch"' > \
$INSTALL_DIR'/vampire_the_masquerade_bloodlines/start.sh'
chmod +x $INSTALL_DIR'/vampire_the_masquerade_bloodlines/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/vampire_the_masquerade_bloodlines
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/vampire_the_masquerade_bloodlines/game \
$WINEPREFIX_DIR/drive_c/Games/vampire_the_masquerade_bloodlines' > \
$INSTALL_DIR'/vampire_the_masquerade_bloodlines/additions.sh'
chmod +x $INSTALL_DIR'/vampire_the_masquerade_bloodlines/additions.sh'

zenity --question \
--title "Vampire: The Masquerade - Bloodlines" \
--text "Install Unofficial Patch?" \
--ok-label "Yes" --cancel-label "No"
if [ $? == 0 ]; then

if [ ! -f $DOWNLOAD_DIR/_distr/vampire_the_masquerade_bloodlines/* ]; then
mkdir -p $DOWNLOAD_DIR/_distr/vampire_the_masquerade_bloodlines
xdg-open $DOWNLOAD_DIR/_distr/vampire_the_masquerade_bloodlines
sensible-browser "http://www.patches-scrolls.de/patch/4647/7/" &
zenity --info --text \
"Download patch and put it in:\n<b>$DOWNLOAD_DIR/_distr/vampire_the_masquerade_bloodlines/</b>\nThen click OK."
fi

export WINEPREFIX="$HOME/.games_nebula/wine_prefix"

mkdir -p $INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp/'
cp $DOWNLOAD_DIR'/_distr/vampire_the_masquerade_bloodlines/'* \
$INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp/'

rm $WINEPREFIX'/drive_c/Games/vampire_the_masquerade_bloodlines'
mkdir -p $WINEPREFIX'/drive_c/Games'
ln -s $INSTALL_DIR'/vampire_the_masquerade_bloodlines/game' \
$WINEPREFIX'/drive_c/Games/vampire_the_masquerade_bloodlines'

cd $INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp/'

zenity --info \
--title "Vampire: The Masquerade - Bloodlines" \
--text "Install into:\n<b>C:\\\Games\\\vampire_the_masquerade_bloodlines</b>"

if [ $WINE_PATH == 'wine' ]; then
    wine ./*.exe
else
    export WINE=$WINE_PATH'/bin/wine'
    export WINELOADER=$WINE_PATH'/bin/wine'
    export WINESERVER=$WINE_PATH'/bin/wineserver'
    export WINEDLLPATH=$WINE_PATH'/lib'
    $WINELOADER ./*.exe
fi

rm -R $INSTALL_DIR'/vampire_the_masquerade_bloodlines/tmp'

fi
