#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/eador_genesis/tmp/app' $INSTALL_DIR'/eador_genesis/game'
rm -R -f $INSTALL_DIR'/eador_genesis/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py eador_genesis "Eador.exe f"' > \
$INSTALL_DIR'/eador_genesis/start.sh'
chmod +x $INSTALL_DIR'/eador_genesis/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/eador_genesis
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/eador_genesis/game \
$WINEPREFIX_DIR/drive_c/Games/eador_genesis' > \
$INSTALL_DIR'/eador_genesis/additions.sh'
chmod +x $INSTALL_DIR'/eador_genesis/additions.sh'
