#!/bin/bash

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/$GAME_NAME
imgmount d $HOME/.games_nebula/games/.dosbox/$GAME_NAME/GAME.DAT -t iso
c:
cls

@ECHO [40;1m
@ECHO  ----------------------------
@ECHO  Shadow Warrior Settings
@ECHO  ----------------------------
@ECHO on
@ECHO off
@ECHO  1) Shadow Warrior
@ECHO  2) Twin Dragon
@ECHO  3) Wanton Destruction
@ECHO on
@ECHO off
@ECHO  ----------------------------
@ECHO  4) exit program
@ECHO  ----------------------------
@ECHO [0m
@ECHO on
@ECHO off
@choice /c1234 /s Which game do you want to run? [1-4]: /n
if errorlevel 4 goto exit
if errorlevel 3 goto wanton
if errorlevel 2 goto tdragon
if errorlevel 1 goto swarrior

:swarrior
cls
@echo off
@COPY sw.dat sw.exe
cls
setup.exe
cls
exit

:tdragon
cls
@echo off
cd .\dragon
cls
setup.exe
cls
exit

:wanton
cls
@echo off
@COPY wanton.dat sw.exe
cls
setup.exe
cls
exit

:exit
exit" > "$DOSBOX_SETTINGS_CONF"
