#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'neighbours_from_hell_2' \
'https://images-3.gog.com/8040c93ea2bd226aef6b169e2254ed3eecbbdb1c866a6489d1f055a73e2b9181.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/neighbours_from_hell_2/tmp/app' $INSTALL_DIR'/neighbours_from_hell_2/game'
rm -R -f $INSTALL_DIR'/neighbours_from_hell_2/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py neighbours_from_hell_2 bin/game.exe' > \
$INSTALL_DIR'/neighbours_from_hell_2/start.sh'
chmod +x $INSTALL_DIR'/neighbours_from_hell_2/start.sh'
