#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/consortium_the_master_edition/tmp/app' $INSTALL_DIR'/consortium_the_master_edition/game'
rm -R -f $INSTALL_DIR'/consortium_the_master_edition/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py consortium_the_master_edition consortium.exe' > \
$INSTALL_DIR'/consortium_the_master_edition/start.sh'
chmod +x $INSTALL_DIR'/consortium_the_master_edition/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/consortium_the_master_edition
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/consortium_the_master_edition/game \
$WINEPREFIX_DIR/drive_c/Games/consortium_the_master_edition' > \
$INSTALL_DIR'/consortium_the_master_edition/additions.sh'
chmod +x $INSTALL_DIR'/consortium_the_master_edition/additions.sh'
