#!/bin/bash

DOWNLOAD_DIR="$1"
INSTALL_DIR="$2"
NEBULA_DIR="$3"

mv "$INSTALL_DIR/dungeon_keeper_2/tmp/app" \
"$INSTALL_DIR/dungeon_keeper_2/game"
rm -R -f "$INSTALL_DIR/dungeon_keeper_2/tmp"

cp "$HOME/.games_nebula/scripts/goglib/dungeon_keeper_2/settings.py" \
"$INSTALL_DIR/dungeon_keeper_2/"

echo -e '#!/bin/bash
NEBULA_DIR="$2"
python "$NEBULA_DIR/launcher_wine.py" dungeon_keeper_2 DKII-DX.EXE' > \
"$INSTALL_DIR/dungeon_keeper_2/start.sh"
chmod +x "$INSTALL_DIR/dungeon_keeper_2/start.sh"

echo -e '#!/bin/bash
INSTALL_DIR="$1"
WINE_DIR="$2"
WINEPREFIX_DIR="$3"
NEBULA_DIR="$4"
python2 "$INSTALL_DIR/dungeon_keeper_2/settings.py" \
"$WINE_DIR" "$WINEPREFIX_DIR" "$NEBULA_DIR"' > \
"$INSTALL_DIR/dungeon_keeper_2/settings.sh"
chmod +x "$INSTALL_DIR/dungeon_keeper_2/settings.sh"
