#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals' \
'https://images-4.gog.com/decd9de49aab84673abb503a719aaebcbcd1fc68b88c061cee0dac8804e001fb.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/tmp/data/noarch/data' \
$INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/game'
rm -R -f $INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/tmp'

echo -e '#!/bin/bash

INSTALL_DIR=$1
NEBULA_DIR=$2

SCUMMVMRC=$INSTALL_DIR/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/scummvmrc
readarray -t ARRAY <<<"$(cat "$SCUMMVMRC")"
LENGHT=${#ARRAY[@]}

for i in $(seq 1 $LENGHT); do
	if [[ ${ARRAY[i]} == "[lsl3]" ]]; then
		FIRST_LINE=$i
	fi
done

cp $HOME/.games_nebula/config/scummvmrc $SCUMMVMRC

for i in $(seq $FIRST_LINE $LENGHT); do 
	echo ${ARRAY[i]} >> "$SCUMMVMRC"
done

python $NEBULA_DIR/launcher_scummvm.py leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals lsl3' > \
$INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/start.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/start.sh'

cp $HOME'/.games_nebula/config/scummvmrc' $INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/'

echo "[lsl3]
description=Leisure Suit Larry 3: Passionate Patti in Pursuit of the Pulsating Pectorals (DOS/English)
gameid=sci
path=$INSTALL_DIR/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/game
savepath=$INSTALL_DIR/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/game" >> \
$INSTALL_DIR'/leisure_suit_larry_3_passionate_patti_in_pursuit_of_the_pulsating_pectorals/scummvmrc'
