#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/tmp/app' \
$INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/game'
rm -R -f $INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py broken_sword_3__the_sleeping_dragon BSTSD.exe' > \
$INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/start.sh'
chmod +x $INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/broken_sword_3__the_sleeping_dragon
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/broken_sword_3__the_sleeping_dragon/game \
$WINEPREFIX_DIR/drive_c/Games/broken_sword_3__the_sleeping_dragon' > \
$INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/additions.sh'
chmod +x $INSTALL_DIR'/broken_sword_3__the_sleeping_dragon/additions.sh'
