#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 "$NEBULA_DIR/modules/goglib_get_banner_2.py" \
'commandos_beyond_the_call_of_duty' \
'https://images-2.gog.com/0cf68854720ee280177accf1df001e6441fa39f41ecacd899999d2dd6c23b4af.jpg' \
"$HOME/.games_nebula/images/goglib_banners"

mv "$INSTALL_DIR/commandos_beyond_the_call_of_duty/tmp/app" \
"$INSTALL_DIR/commandos_beyond_the_call_of_duty/game"
rm -R -f "$INSTALL_DIR/commandos_beyond_the_call_of_duty/tmp"

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py commandos_beyond_the_call_of_duty coman_mp.exe' > \
"$INSTALL_DIR/commandos_beyond_the_call_of_duty/start.sh"
chmod +x "$INSTALL_DIR/commandos_beyond_the_call_of_duty/start.sh"
