#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/planescape_torment/tmp/data/noarch/prefix/drive_c/GOG Games/Planescape Torment' \
$INSTALL_DIR'/planescape_torment/game'
rm -R -f $INSTALL_DIR'/planescape_torment/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr/planescape_torment'

if [ ! -f $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' -C - \
	'http://www.weidu.org/%7Ethebigg/WeiDU-Linux-240.zip'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' -C - \
	'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=869'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/planescape_torment/Ghostdogs_PST_UI_mod_v2.2.7z' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/planescape_torment/Ghostdogs_PST_UI_mod_v2.2.7z' -C - \
	'http://www.shsforums.net/files/download/683-ghostdogs-pst-ui-mod-v22/'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/planescape_torment/pstfixpack_v413.rar' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/planescape_torment/pstfixpack_v413.rar' -C - \
	'http://www.shsforums.net/files/download/647-pst-ultimate-weidu-fixpack-v413/'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/planescape_torment/pstub_v412.rar' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/planescape_torment/pstub_v412.rar' -C - \
	'http://www.shsforums.net/files/download/648-pst-unfinished-business-v412/'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/planescape_torment/psttweak_v412.rar' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/planescape_torment/psttweak_v412.rar' -C - \
	'http://www.shsforums.net/files/download/649-qwinns-pst-tweak-pack-v412/'
fi

if [ $(uname -m) == "x86_64" ]; then
	ARCH='amd64'
else
	ARCH='i386'
fi

7z e -aoa -o$INSTALL_DIR'/planescape_torment/game' \
$DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' \
'WeiDU-Linux/bin/'$ARCH'/weidu' 'WeiDU-Linux/bin/'$ARCH'/tolower'

tar -xzvf $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' \
-C $INSTALL_DIR'/baldurs_gate_the_original_saga/game'

7z x -aoa -o$INSTALL_DIR'/planescape_torment/game' \
$DOWNLOAD_DIR'/_distr/planescape_torment/Ghostdogs_PST_UI_mod_v2.2.7z'

7z x -aoa -o$INSTALL_DIR'/planescape_torment/game' \
$DOWNLOAD_DIR'/_distr/planescape_torment/pstfixpack_v413.rar'

7z x -aoa -o$INSTALL_DIR'/planescape_torment/game' \
$DOWNLOAD_DIR'/_distr/planescape_torment/pstub_v412.rar'

7z x -aoa -o$INSTALL_DIR'/planescape_torment/game' \
$DOWNLOAD_DIR'/_distr/planescape_torment/psttweak_v412.rar'

echo -e '#!/bin/bash
./tolower
./weidu ./widescreen/widescreen.tp2' > \
$INSTALL_DIR'/planescape_torment/game/widescreen.sh'
chmod +x $INSTALL_DIR'/planescape_torment/game/widescreen.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./"'"setup-ghostdog's-pst-ui.tp2"'"' > \
$INSTALL_DIR'/planescape_torment/game/gui_fix.sh'
chmod +x $INSTALL_DIR'/planescape_torment/game/gui_fix.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./setup-pst-fix.tp2' > \
$INSTALL_DIR'/planescape_torment/game/fixpack.sh'
chmod +x $INSTALL_DIR'/planescape_torment/game/fixpack.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./setup-pst-ub.tp2' > \
$INSTALL_DIR'/planescape_torment/game/ub.sh'
chmod +x $INSTALL_DIR'/planescape_torment/game/ub.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./setup-pst-tweak.tp2' > \
$INSTALL_DIR'/planescape_torment/game/tweakpack.sh'
chmod +x $INSTALL_DIR'/planescape_torment/game/tweakpack.sh'

echo "[Alias]
HD0:=C:\Games\planescape_torment
CD1:=C:\Games\planescape_torment\data
CD2:=C:\Games\planescape_torment\data
CD3:=C:\Games\planescape_torment\data
CD4:=C:\Games\planescape_torment\data
CD5:=C:\Games\planescape_torment\data
[Program Options]
3D Acceleration=1" > $INSTALL_DIR'/planescape_torment/game/Torment.ini'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py planescape_torment Torment.exe
fi' > $INSTALL_DIR'/planescape_torment/start.sh'
chmod +x $INSTALL_DIR'/planescape_torment/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

rm $WINEPREFIX/drive_c/Games/planescape_torment
mkdir -p $WINEPREFIX/drive_c/Games
ln -s $INSTALL_DIR/planescape_torment/game \
$WINEPREFIX/drive_c/Games/planescape_torment

if [ ! -f $INSTALL_DIR/planescape_torment/.widescreen_installed ]; then
zenity --question \
--text="Install Widescreen Mode?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/planescape_torment/game
rm -R ./cache
ln -s ./data ./cache
xterm -fg green -bg black -fn 10x20 -e ./widescreen.sh
rm ./cache
mkdir ./cache
touch $INSTALL_DIR/planescape_torment/.widescreen_installed
fi
fi

if [ ! -f $INSTALL_DIR/planescape_torment/.gui_fix_installed ]; then
zenity --question \
--text="'"Install GhostDog's PS:T UI?"'" --ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/planescape_torment/game
xterm -fg green -bg black -fn 10x20 -e ./gui_fix.sh
touch $INSTALL_DIR/planescape_torment/.gui_fix_installed
fi
fi

if [ ! -f $INSTALL_DIR/planescape_torment/.fixpack_installed ]; then
zenity --question \
--text="Install PS:T Ultimate WeiDU Fixpack?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/planescape_torment/game
xterm -fg green -bg black -fn 10x20 -e ./fixpack.sh
touch $INSTALL_DIR/planescape_torment/.fixpack_installed
fi
fi

if [ ! -f $INSTALL_DIR/planescape_torment/.ub_installed ]; then
zenity --question \
--text="Install PS:T Unfinished Business?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/planescape_torment/game
xterm -fg green -bg black -fn 10x20 -e ./ub.sh
touch $INSTALL_DIR/planescape_torment/.ub_installed
fi
fi

if [ ! -f $INSTALL_DIR/planescape_torment/.tweakpack_installed ]; then
zenity --question \
--text="'"Install Qwinn's PS:T Tweak Pack?"'" --ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/planescape_torment/game
xterm -fg green -bg black -fn 10x20 -e ./tweakpack.sh
touch $INSTALL_DIR/planescape_torment/.tweakpack_installed
fi
fi' > $INSTALL_DIR'/planescape_torment/additions.sh'
chmod +x $INSTALL_DIR'/planescape_torment/additions.sh'
