#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_weidu

get_common_file 'lin-widescreen-v3.07.tar.gz' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=869'

get_file 'Ghostdogs_PST_UI_mod_v2.2.7z' \
'http://www.shsforums.net/files/download/683-ghostdogs-pst-ui-mod-v22/'

get_file 'pstfixpack_v413.rar' \
'http://www.shsforums.net/files/download/647-pst-ultimate-weidu-fixpack-v413/'

get_file 'pstub_v412.rar' \
'http://www.shsforums.net/files/download/648-pst-unfinished-business-v412/'

get_file 'psttweak_v412.rar' \
'http://www.shsforums.net/files/download/649-qwinns-pst-tweak-pack-v412/'

tar -xzvf "$DOWNLOAD_DIR/_distr/lin-widescreen-v3.07.tar.gz" -C "$INSTALL_DIR/$GAME_NAME/game"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/Ghostdogs_PST_UI_mod_v2.2.7z"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/pstfixpack_v413.rar"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/pstub_v412.rar"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/psttweak_v412.rar"

echo "[Alias]
HD0:=C:\Games\\$GAME_NAME
CD1:=C:\Games\\$GAME_NAME\data
CD2:=C:\Games\\$GAME_NAME\data
CD3:=C:\Games\\$GAME_NAME\data
CD4:=C:\Games\\$GAME_NAME\data
CD5:=C:\Games\\$GAME_NAME\data
[Program Options]
3D Acceleration=1" > "$INSTALL_DIR/$GAME_NAME/game/Torment.ini"

cd "$INSTALL_DIR/$GAME_NAME/game"
printf 'y\nn\n' | ./tolower
