#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VER=$(python2 "$NEBULA_DIR/dialogs.py" list "GOG, GameCopyWorld")

if [ "$VER" == "GameCopyWorld" ]; then

get_from_mega 'corsairs_gcw.7z' \
'https://mega.nz/#!XlhABJTL!-fqkUun1BLIbp6CQ6XCl3oEw36MIkoQ0Hd32V5orIok'

7z e -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/corsairs_gcw.7z"

echo '[PATHS]
PATHROOT=c:\Games\corsairs_gold\
PATHDATA=c:\Games\corsairs_gold\DATA\
PATHSAVE=c:\Games\corsairs_gold\SAVINGS\
PATHCDROM=c:\Games\corsairs_gold\
PATHBOOK=c:\Games\corsairs_gold\BOOK\
PATHSOUND=c:\Games\corsairs_gold\SOUND\
[GENERAL]
LANGUAGE=English' > \
"$INSTALL_DIR/$GAME_NAME/game/corsairs.ini"

fi
