#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/system_shock_2/tmp/app' $INSTALL_DIR'/system_shock_2/game'
rm -R -f $INSTALL_DIR'/system_shock_2/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py system_shock_2 start.exe' > \
$INSTALL_DIR'/system_shock_2/start.sh'
chmod +x $INSTALL_DIR'/system_shock_2/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/system_shock_2
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/system_shock_2/game \
$WINEPREFIX_DIR/drive_c/Games/system_shock_2' > \
$INSTALL_DIR'/system_shock_2/additions.sh'
chmod +x $INSTALL_DIR'/system_shock_2/additions.sh'
