#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_file 'HoMM3 HD Latest.exe' \
'http://h3hota.com/HD/HoMM3%20HD%20Latest.exe'

mkdir -p "$INSTALL_DIR/$GAME_NAME/tmp"
innoextract "$DOWNLOAD_DIR/_distr/$GAME_NAME/HoMM3 HD Latest.exe" -d \
"$INSTALL_DIR/$GAME_NAME/tmp"
mv "$INSTALL_DIR/$GAME_NAME/tmp/app/"* "$INSTALL_DIR/$GAME_NAME/game/"
rm -R "$INSTALL_DIR/$GAME_NAME/tmp"

echo -e '#!/bin/bash
if [ -f "$INSTALL_DIR/'"$GAME_NAME"'/game/Heroes3 HD.exe" ]; then
python2 "$NEBULA_DIR/launcher_wine.py" '"$GAME_NAME"' "Heroes3 HD.exe"
else
if [ -f "$INSTALL_DIR/'"$GAME_NAME"'/game/HD_Launcher.exe" ]; then
python2 "$NEBULA_DIR/launcher_wine.py" '"$GAME_NAME"' "HD_Launcher.exe"
else
python2 "$NEBULA_DIR/launcher_wine.py" '"$GAME_NAME"' "Heroes3.exe"
fi
fi' > "$START_FILE" && chmod +x "$START_FILE"
