#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/lure_of_the_temptress/tmp/data/noarch/data' \
$INSTALL_DIR'/lure_of_the_temptress/game'
rm -R -f $INSTALL_DIR'/lure_of_the_temptress/tmp'

echo -e '#!/bin/bash

INSTALL_DIR=$1
NEBULA_DIR=$2

SCUMMVMRC=$INSTALL_DIR/lure_of_the_temptress/scummvmrc
readarray -t ARRAY <<<"$(cat "$SCUMMVMRC")"
LENGHT=${#ARRAY[@]}

for i in $(seq 1 $LENGHT); do
	if [[ ${ARRAY[i]} == "[lure]" ]]; then
		FIRST_LINE=$i
	fi
done

cp $HOME/.games_nebula/config/scummvmrc $SCUMMVMRC

for i in $(seq $FIRST_LINE $LENGHT); do 
	echo ${ARRAY[i]} >> "$SCUMMVMRC"
done

python $NEBULA_DIR/launcher_scummvm.py lure_of_the_temptress lure' > \
$INSTALL_DIR'/lure_of_the_temptress/start.sh'
chmod +x $INSTALL_DIR'/lure_of_the_temptress/start.sh'

cp $HOME'/.games_nebula/config/scummvmrc' $INSTALL_DIR'/lure_of_the_temptress/'

echo "[lure]
gameid=lure
description=Lure of the Temptress (VGA/DOS/English)
path=$INSTALL_DIR/lure_of_the_temptress/game
savepath=$INSTALL_DIR/lure_of_the_temptress/game" >> \
$INSTALL_DIR'/lure_of_the_temptress/scummvmrc'
