#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_upx

cd "$INSTALL_DIR/$GAME_NAME/game"
./upx -d pop2.exe

get_from_mega 'pop2_widescreen.7z' \
'https://mega.nz/#!mN4g1Qwb!ssTueG8xp_nAjvMBuPm0xg1tMn_mKv14zhuvwv6HrV0'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/pop2_widescreen.7z" \
'pop2.7z'

7z x -aoa -p'pop2' -o"$INSTALL_DIR/$GAME_NAME/game/" \
"$INSTALL_DIR/$GAME_NAME/game/pop2.7z"

echo -e '#!/bin/bash
export WINEDLLOVERRIDES="pop2w=n,b"
export WINEDLLOVERRIDES="d3d9=n,b"
python2 "$NEBULA_DIR/launcher_wine.py" '"$GAME_NAME"' "PrinceOfPersia.exe"' > \
"$START_FILE"
