#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'leisure_suit_larry_6_shape_up_or_slip_out' \
'https://images-4.gog.com/32595f3aac24a02124937700589996a18838df7baefdc80c7392083d197f1bf2.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/tmp/data/noarch/data' \
$INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/game'
rm -R -f $INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/leisure_suit_larry_6_shape_up_or_slip_out
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/leisure_suit_larry_6_shape_up_or_slip_out/game \
$HOME/.games_nebula/games/.dosbox/leisure_suit_larry_6_shape_up_or_slip_out
python $NEBULA_DIR/launcher_dosbox.py leisure_suit_larry_6_shape_up_or_slip_out' > \
$INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/start.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/leisure_suit_larry_6_shape_up_or_slip_out
c:
cls
sierra.exe
exit" > $INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/leisure_suit_larry_6_shape_up_or_slip_out
c:
cls
install.exe
exit" > $INSTALL_DIR'/leisure_suit_larry_6_shape_up_or_slip_out/dosbox_settings.conf'
