#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/ultima_4/tmp/app' $INSTALL_DIR'/ultima_4/game'
rm -R -f $INSTALL_DIR'/ultima_4/tmp'

cp $INSTALL_DIR'/ultima_4/tmp/app' $INSTALL_DIR'/ultima_4/game/__support/save/'* \
$INSTALL_DIR'/ultima_4/tmp/app' $INSTALL_DIR'/ultima_4/game/'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/ultima_4
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/ultima_4/game \
$HOME/.games_nebula/games/.dosbox/ultima_4
python $NEBULA_DIR/launcher_dosbox.py ultima_4' > \
$INSTALL_DIR'/ultima_4/start.sh'
chmod +x $INSTALL_DIR'/ultima_4/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/ultima_4
cls
c:
ultima.com
exit" > $INSTALL_DIR'/ultima_4/dosbox_game.conf'
