#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'baldurs_gate_the_original_saga' \
'https://images-2.gog.com/cd7f35b06f0a5ca0d1c8b875cbe0ab9967e6cd02d565bd0d5c830b0fe5562c72.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR"/baldurs_gate_the_original_saga/tmp/data/noarch/prefix/drive_c/GOG Games/Baldur's Gate" \
$INSTALL_DIR'/baldurs_gate_the_original_saga/game'
rm -R -f $INSTALL_DIR'/baldurs_gate_the_original_saga/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga'

if [ ! -f $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' -C - \
	'http://www.weidu.org/%7Ethebigg/WeiDU-Linux-240.zip'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' -C - \
	'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=869'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/TWM_GUI_beta0,994.exe' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/TWM_GUI_beta0,994.exe' -C - \
	'http://baldur.cob-bg.pl/download/bg1/misc/TWM_GUI_beta0,994.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip' -C - \
	'http://mods.pocketplane.net/bg1ubfiles/bg1ub-v14.zip'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/lin-bg1tweaks-v5.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/lin-bg1tweaks-v5.zip' -C - \
	'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=741'
fi

if [ $(uname -m) == "x86_64" ]; then
	ARCH='amd64'
else
	ARCH='i386'
fi

7z e -aoa -o$INSTALL_DIR'/baldurs_gate_the_original_saga/game' \
$DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' \
'WeiDU-Linux/bin/'$ARCH'/weidu' 'WeiDU-Linux/bin/'$ARCH'/tolower'

tar -xzvf $DOWNLOAD_DIR'/_distr/lin-widescreen-v3.07.tar.gz' \
-C $INSTALL_DIR'/baldurs_gate_the_original_saga/game'

7z x -aoa -o$INSTALL_DIR'/baldurs_gate_the_original_saga/game' \
$DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/bg1ub-v14.zip'

7z x -aoa -o$INSTALL_DIR'/baldurs_gate_the_original_saga/game' \
$DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/lin-bg1tweaks-v5.zip'

cp $DOWNLOAD_DIR'/_distr/baldurs_gate_the_original_saga/TWM_GUI_beta0,994.exe' \
$INSTALL_DIR'/baldurs_gate_the_original_saga/game/'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/game/TWM_GUI_beta0,994.exe'

echo -e '#!/bin/bash
./tolower
./weidu ./widescreen/widescreen.tp2' > \
$INSTALL_DIR'/baldurs_gate_the_original_saga/game/widescreen.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/game/widescreen.sh'

echo -e '#!/bin/bash
WINELOADER=$1
zenity --info --text "Extract to current directory!"
export WINEDEBUG=-all
$WINELOADER ./twm_gui_beta0,994.exe
./tolower
if [ ! -f ./twm_gui/setup-twm_gui.tp2 ]; then
	zenity --error --text "Something gone wrong..."
else
	./weidu ./twm_gui/setup-twm_gui.tp2
fi' > $INSTALL_DIR'/baldurs_gate_the_original_saga/game/gui_fix.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/game/gui_fix.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./bg1ub/setup-bg1ub.tp2' > \
$INSTALL_DIR'/baldurs_gate_the_original_saga/game/ub.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/game/ub.sh'

echo -e '#!/bin/bash
./tolower
./weidu ./bg1tweaks/setup-bg1tweaks.tp2' > \
$INSTALL_DIR'/baldurs_gate_the_original_saga/game/tweakpack.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/game/tweakpack.sh'

echo "[Alias]
HD0:=C:\Games\baldurs_gate_the_original_saga
CD1:=C:\Games\baldurs_gate_the_original_saga\data
CD2:=C:\Games\baldurs_gate_the_original_saga\data
CD3:=C:\Games\baldurs_gate_the_original_saga\data
CD4:=C:\Games\baldurs_gate_the_original_saga\data
CD5:=C:\Games\baldurs_gate_the_original_saga\data
CD6:=C:\Games\baldurs_gate_the_original_saga\data
[Program Options]
3D Acceleration=1" > $INSTALL_DIR'/baldurs_gate_the_original_saga/game/Baldur.ini'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py baldurs_gate_the_original_saga BGMain.exe' > \
$INSTALL_DIR'/baldurs_gate_the_original_saga/start.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

rm $WINEPREFIX_DIR/drive_c/Games/baldurs_gate_the_original_saga
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/baldurs_gate_the_original_saga/game \
$WINEPREFIX_DIR/drive_c/Games/baldurs_gate_the_original_saga

if [ ! -f $INSTALL_DIR/baldurs_gate_the_original_saga/.widescreen_installed ]; then
zenity --question \
--text="Install Widescreen Mode?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/baldurs_gate_the_original_saga/game
xterm -fg green -bg black -fn 10x20 -e ./widescreen.sh
touch $INSTALL_DIR/baldurs_gate_the_original_saga/.widescreen_installed
fi
fi

if [ ! -f $INSTALL_DIR/baldurs_gate_the_original_saga/.gui_fix_installed ]; then
zenity --question \
--text="Install GUI Fix?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/baldurs_gate_the_original_saga/game
xterm -fg green -bg black -fn 10x20 -e ./gui_fix.sh $WINELOADER
touch $INSTALL_DIR/baldurs_gate_the_original_saga/.gui_fix_installed
fi
fi

if [ ! -f $INSTALL_DIR/baldurs_gate_the_original_saga/.ub_installed ]; then
zenity --question \
--text="Install BG1 Unfinished Business?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/baldurs_gate_the_original_saga/game
xterm -fg green -bg black -fn 10x20 -e ./ub.sh
touch $INSTALL_DIR/baldurs_gate_the_original_saga/.ub_installed
fi
fi

if [ ! -f $INSTALL_DIR/baldurs_gate_the_original_saga/.tweaks_installed ]; then
zenity --question \
--text="Install BG1 Tweak Pack?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/baldurs_gate_the_original_saga/game
xterm -fg green -bg black -fn 10x20 -e ./tweakpack.sh
touch $INSTALL_DIR/baldurs_gate_the_original_saga/.tweaks_installed
fi
fi' > $INSTALL_DIR'/baldurs_gate_the_original_saga/additions.sh'
chmod +x $INSTALL_DIR'/baldurs_gate_the_original_saga/additions.sh'
