#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_weidu

get_common_file 'lin-widescreen-v3.07.tar.gz' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=869'

get_file 'TWM_GUI_beta0,994.exe' \
'http://baldur.cob-bg.pl/download/bg1/misc/TWM_GUI_beta0,994.exe'

get_file 'bg1ub-v14.zip' \
'http://mods.pocketplane.net/bg1ubfiles/bg1ub-v14.zip'

get_file 'lin-bg1tweaks-v5.zip' \
'http://gibberlings3.net/forums/index.php?app=downloads&module=display&section=download&do=confirm_download&id=741'

tar -xzvf "$DOWNLOAD_DIR/_distr/lin-widescreen-v3.07.tar.gz" -C "$INSTALL_DIR/$GAME_NAME/game"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/bg1ub-v14.zip"

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/lin-bg1tweaks-v5.zip"

cp "$DOWNLOAD_DIR/_distr/$GAME_NAME/TWM_GUI_beta0,994.exe" "$INSTALL_DIR/$GAME_NAME/game/"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/TWM_GUI_beta0,994.exe"

echo "[Alias]
HD0:=C:\Games\\$GAME_NAME
CD1:=C:\Games\\$GAME_NAME\data
CD2:=C:\Games\\$GAME_NAME\data
CD3:=C:\Games\\$GAME_NAME\data
CD4:=C:\Games\\$GAME_NAME\data
CD5:=C:\Games\\$GAME_NAME\data
CD6:=C:\Games\\$GAME_NAME\data
[Program Options]
3D Acceleration=1" > "$INSTALL_DIR/$GAME_NAME/game/Baldur.ini"

cd "$INSTALL_DIR/$GAME_NAME/game"
printf 'y\nn\n' | ./tolower

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./widescreen/widescreen.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/widescreen.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/widescreen.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
if [ ! -d "$INSTALL_DIR/$GAME_NAME/game/twm_gui" ]; then
$WINELOADER ./twm_gui_beta0,994.exe
printf "y\nn\n" | ./tolower
fi
./weidu ./twm_gui/setup-twm_gui.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/gui_fix.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/gui_fix.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./bg1ub/setup-bg1ub.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/ub.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/ub.sh"

echo -e '#!/bin/bash
cd "$INSTALL_DIR/$GAME_NAME/game"
printf "y\nn\n" | ./tolower
./weidu ./bg1tweaks/setup-bg1tweaks.tp2' > \
"$INSTALL_DIR/$GAME_NAME/game/tweakpack.sh"
chmod +x "$INSTALL_DIR/$GAME_NAME/game/tweakpack.sh"
