#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'alien_breed_tower_assault_game' \
'https://images-1.gog.com/6d58e32c1524882e736f5a7512a5c4965cb33f253232db93fd922e90605bfb6a.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/alien_breed_tower_assault_game/tmp/app' \
$INSTALL_DIR'/alien_breed_tower_assault_game/game'
rm -R -f $INSTALL_DIR'/alien_breed_tower_assault_game/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/alien_breed_tower_assault_game
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/alien_breed_tower_assault_game/game \
$HOME/.games_nebula/games/.dosbox/alien_breed_tower_assault_game
python $NEBULA_DIR/launcher_dosbox.py alien_breed_tower_assault_game' > \
$INSTALL_DIR'/alien_breed_tower_assault_game/start.sh'
chmod +x $INSTALL_DIR'/alien_breed_tower_assault_game/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/alien_breed_tower_assault_game
c:
cls
TA.exe
exit" > $INSTALL_DIR'/alien_breed_tower_assault_game/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/alien_breed_tower_assault_game
c:
cls
setsound
exit" > $INSTALL_DIR'/alien_breed_tower_assault_game/dosbox_settings.conf'
