#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'neighbours_from_hell_1' \
'https://images-2.gog.com/121870b3b51d7f73085455c4b080640c47c69d1b1162a57c2d60ba73d461e3c5.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/neighbours_from_hell_1/tmp/app' $INSTALL_DIR'/neighbours_from_hell_1/game'
rm -R -f $INSTALL_DIR'/neighbours_from_hell_1/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py neighbours_from_hell_1 bin/game.exe' > \
$INSTALL_DIR'/neighbours_from_hell_1/start.sh'
chmod +x $INSTALL_DIR'/neighbours_from_hell_1/start.sh'
