#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/mainlining_demo/tmp/app' $INSTALL_DIR'/mainlining_demo/game'
rm -R -f $INSTALL_DIR'/mainlining_demo/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py mainlining_demo MainliningGame.exe' > \
$INSTALL_DIR'/mainlining_demo/start.sh'
chmod +x $INSTALL_DIR'/mainlining_demo/start.sh'
