#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VER=$(python2 "$NEBULA_DIR/dialogs.py" list "DOSBox, KeeperFX (+400 Mb)")

if [ "$VER" == "KeeperFX (+400 Mb)" ]; then

get_file 'keeperfx_ccp_0_4_6_complete.7z' \
'http://keeperfx.keeperklan.com/keeperfx_ccp_0_4_6_complete.7z'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/keeperfx_ccp_0_4_6_complete.7z" \
& proc_timer $! "Extracting keeperfx_ccp_0_4_6_complete.7z"

mv "$INSTALL_DIR/$GAME_NAME/game/"*.ogg "$INSTALL_DIR/$GAME_NAME/game/music"
cp "$HOME/.games_nebula/scripts/goglib/$GAME_NAME/settings.dat" \
"$INSTALL_DIR/$GAME_NAME/game/save"

echo -e '#!/bin/bash
python2 "$NEBULA_DIR/launcher_wine.py" '"$GAME_NAME"' "keeperfx.exe -nocd"' > \
"$START_FILE"

else

rm "$INSTALL_DIR/$GAME_NAME/settings.py"

echo "[autoexec]
@echo off
mount c $HOME/.games_nebula/games/.dosbox/$GAME_NAME
c:
imgmount d $HOME/.games_nebula/games/.dosbox/$GAME_NAME/GAME.INST -fs iso
cls

echo.
echo.
ECHO  ---------------------------------
ECHO  Dungeon Keeper
ECHO  ---------------------------------
ECHO  1) Dungeon Keeper
ECHO  2) The Deeper Dungeons
ECHO  ---------------------------------
ECHO  3) Exit
ECHO  ---------------------------------
echo.
echo.

choice /c123 /s Select number [1-3]: /n
if errorlevel 3 goto exit
if errorlevel 2 goto dd
if errorlevel 1 goto dk

:dk
cls
KEEPER.EXE
cls
exit

:dd
cls
DEEPER.EXE
cls
exit

:exit
exit" > "$INSTALL_DIR/$GAME_NAME/dosbox_game.conf"

fi
