#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/bio_menace/tmp/data/noarch/data' $INSTALL_DIR'/bio_menace/game'
rm -R -f $INSTALL_DIR'/bio_menace/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/bio_menace
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/bio_menace/game \
$HOME/.games_nebula/games/.dosbox/bio_menace
python $NEBULA_DIR/launcher_dosbox.py bio_menace' > \
$INSTALL_DIR'/bio_menace/start.sh'
chmod +x $INSTALL_DIR'/bio_menace/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/bio_menace
c:
cls
ECHO [1;33m[42mÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
ECHO º ------------------------------------------ º
ECHO º Bio Menace - Full Pack                     º
ECHO º ------------------------------------------ º
ECHO º  1) Bio Menace Part 1                      º
ECHO º  2) Bio Menace Part 2                      º
ECHO º  3) Bio Menace Part 3                      º
ECHO º ------------------------------------------ º
ECHO º  4) exit program                           º
ECHO º ------------------------------------------ º
ECHO ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼[0m

choice /c1234 /s Which game do you want to run? [1-4]: /n 
if errorlevel 4 goto exit
if errorlevel 3 goto b3
if errorlevel 2 goto b2
if errorlevel 1 goto b1

:b1
@echo off
BMENACE1.EXE
exit

:b2
@echo off
BMENACE2.EXE
exit

:b3
@echo off
BMENACE3.EXE
exit

:exit
exit" > $INSTALL_DIR'/bio_menace/dosbox_game.conf'
