#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_weidu
get_upx

get_file 'HighRes1.1a.exe' \
'http://koti.mbnet.fi/ton_hur/files/Arcanum/HighRes1.1a.exe'

get_file 'uap091225.exe' \
'http://koti.mbnet.fi/ton_hur/files/Arcanum/UAP091225.exe'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/game" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/HighRes1.1a.exe" \
& proc_timer $! "Extracting HighRes1.1a.exe"

cp "$DOWNLOAD_DIR/_distr/$GAME_NAME/uap091225.exe" \
"$INSTALL_DIR/$GAME_NAME/game/" \
& proc_timer $! "Copying uap091225.exe"

cd "$INSTALL_DIR/$GAME_NAME/game"
printf 'y\nn\n' | ./tolower > /dev/null 2>&1

./upx -d ./arcanum.exe
