#!/bin/bash

DOWNLOAD_DIR="$1"
INSTALL_DIR="$2"

mv "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/tmp/app" \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game"
rm -R -f "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/tmp"

mkdir -p "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura"

if [ ! -f "$DOWNLOAD_DIR/_distr/WeiDU-Linux-240.zip" ]; then
    curl -L -o "$DOWNLOAD_DIR/_distr/WeiDU-Linux-240.zip" -C - \
    'http://www.weidu.org/%7Ethebigg/WeiDU-Linux-240.zip'
fi

if [ ! -f "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe" ]; then
    curl -L -o "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe" -C - \
    'http://koti.mbnet.fi/ton_hur/files/Arcanum/HighRes1.1a.exe'
fi

if [ ! -f "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe" ]; then
    curl -L -o "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe" -C - \
    'http://koti.mbnet.fi/ton_hur/files/Arcanum/UAP091225.exe'
fi

if [ $(uname -m) == "x86_64" ]; then
    ARCH="amd64"
else
    ARCH="i386"
fi

7z e -aoa -o"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game" \
"$DOWNLOAD_DIR/_distr/WeiDU-Linux-240.zip" \
"WeiDU-Linux/bin/$ARCH/weidu" "WeiDU-Linux/bin/$ARCH/tolower"

7z x -aoa -o"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game" \
"$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe"

cp "$DOWNLOAD_DIR/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe" \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/"

echo -e '#!/bin/bash
./weidu --nogame ./setup-highres.tp2' > \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/highres.sh"
chmod +x "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/highres.sh"

cp "$HOME/.games_nebula/scripts/goglib/arcanum_of_steamworks_and_magick_obscura/settings.py" \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/"
chmod +x "$HOME/.games_nebula/scripts/goglib/arcanum_of_steamworks_and_magick_obscura/settings.py"

echo -e '#!/bin/bash
NEBULA_DIR="$2"
python "$NEBULA_DIR/launcher_wine.py" arcanum_of_steamworks_and_magick_obscura arcanum.exe' > \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/start.sh"
chmod +x "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/start.sh"

echo -e '#!/bin/bash
WINE_DIR="$2"
WINEPREFIX_DIR="$3"
NEBULA_DIR="$4"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
python "$DIR/settings.py" \
"$WINE_DIR" "$WINEPREFIX_DIR" "$NEBULA_DIR"' > \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/settings.sh"
chmod +x "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/settings.sh"

echo -e '#!/bin/bash
INSTALL_DIR="$1"
WINEPREFIX_DIR="$3"
rm "$WINEPREFIX_DIR/drive_c/Games/arcanum_of_steamworks_and_magick_obscura"
mkdir -p "$WINEPREFIX_DIR/drive_c/Games"
ln -s "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game" \
"$WINEPREFIX_DIR/drive_c/Games/arcanum_of_steamworks_and_magick_obscura"' > \
"$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/additions.sh"
chmod +x "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/additions.sh"

cd "$INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game"
printf 'y\nn\n' | ./tolower
