#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/tmp/app' \
$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game'
rm -R -f $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura'

if [ ! -f $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' -C - \
	'http://www.weidu.org/%7Ethebigg/WeiDU-Linux-240.zip'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe' -C - \
	'http://koti.mbnet.fi/ton_hur/files/Arcanum/HighRes1.1a.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe' ]; then	
	curl -L -o $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe' -C - \
	'http://koti.mbnet.fi/ton_hur/files/Arcanum/UAP091225.exe'
fi

if [ $(uname -m) == "x86_64" ]; then
	ARCH='amd64'
else
	ARCH='i386'
fi

7z e -aoa -o$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game' \
$DOWNLOAD_DIR'/_distr/WeiDU-Linux-240.zip' \
'WeiDU-Linux/bin/'$ARCH'/weidu' 'WeiDU-Linux/bin/'$ARCH'/tolower'

7z x -aoa -o$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game' \
$DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/HighRes1.1a.exe'

cp $DOWNLOAD_DIR'/_distr/arcanum_of_steamworks_and_magick_obscura/uap091225.exe' \
$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game/'

echo -e '#!/bin/bash
./tolower
./weidu --nogame ./setup-highres.tp2' > \
$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game/highres.sh'
chmod +x $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/game/highres.sh'

cp $HOME'/.games_nebula/scripts/goglib/arcanum_of_steamworks_and_magick_obscura/settings.py' \
$INSTALL_DIR/'arcanum_of_steamworks_and_magick_obscura/'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py arcanum_of_steamworks_and_magick_obscura Arcanum.exe' > \
$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/start.sh'
chmod +x $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/start.sh'

echo -e '#!/bin/bash
WINE_DIR=$2
WINEPREFIX_DIR=$3
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
python $DIR/settings.py $WINE_DIR $WINEPREFIX_DIR' > \
$INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/settings.sh'
chmod +x $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

rm $WINEPREFIX_DIR/drive_c/Games/arcanum_of_steamworks_and_magick_obscura
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game \
$WINEPREFIX_DIR/drive_c/Games/arcanum_of_steamworks_and_magick_obscura

if [ ! -f $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/.patch_installed ]; then
zenity --question \
--text="Install Unofficial Arcanum Patch v091225?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
zenity --info --text "Install to default location!"
if [ -f $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/uap091225.exe ]; then
$WINELOADER $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/uap091225.exe /D=\
$INSTALL_DIR_WIN\\\\arcanum_of_steamworks_and_magick_obscura\\\\game
else
$WINELOADER $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game/UAP091225.exe /D=\
$INSTALL_DIR_WIN\\\\arcanum_of_steamworks_and_magick_obscura\\\\game
fi
touch $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/.patch_installed
fi
fi

if [ ! -f $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/.hd_installed ]; then
zenity --question \
--text="Install High Resolution Patch?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
cd $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/game
xterm -fg green -bg black -fn 10x20 -e ./highres.sh
touch $INSTALL_DIR/arcanum_of_steamworks_and_magick_obscura/.hd_installed
fi
fi' > $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/additions.sh'
chmod +x $INSTALL_DIR'/arcanum_of_steamworks_and_magick_obscura/additions.sh'
