#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/kathy_rain_demo/tmp/app' $INSTALL_DIR'/kathy_rain_demo/game'
rm -R -f $INSTALL_DIR'/kathy_rain_demo/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py kathy_rain_demo KathyRain.exe' > \
$INSTALL_DIR'/kathy_rain_demo/start.sh'
chmod +x $INSTALL_DIR'/kathy_rain_demo/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/kathy_rain_demo/game
$WINELOADER winsetup.exe' > $INSTALL_DIR'/kathy_rain_demo/settings.sh'
chmod +x $INSTALL_DIR'/kathy_rain_demo/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/kathy_rain_demo
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/kathy_rain_demo/game \
$WINEPREFIX_DIR/drive_c/Games/kathy_rain_demo' > \
$INSTALL_DIR'/kathy_rain_demo/additions.sh'
chmod +x $INSTALL_DIR'/kathy_rain_demo/additions.sh'
