#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'leisure_suit_larry_6_vga_shape_up_or_slip_out' \
'https://images-4.gog.com/78808de86465abb52dd6d2ce7f21f39ea19fab45bc4dbfd4e298ad4ec2319a41.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/tmp/data/noarch/data' \
$INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/game'
rm -R -f $INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/tmp'

echo -e '#!/bin/bash

INSTALL_DIR=$1
NEBULA_DIR=$2

SCUMMVMRC=$INSTALL_DIR/leisure_suit_larry_6_vga_shape_up_or_slip_out/scummvmrc
readarray -t ARRAY <<<"$(cat "$SCUMMVMRC")"
LENGHT=${#ARRAY[@]}

for i in $(seq 1 $LENGHT); do
	if [[ ${ARRAY[i]} == "[lsl6-cd]" ]]; then
		FIRST_LINE=$i
	fi
done

cp $HOME/.games_nebula/config/scummvmrc $SCUMMVMRC

for i in $(seq $FIRST_LINE $LENGHT); do 
	echo ${ARRAY[i]} >> "$SCUMMVMRC"
done

python $NEBULA_DIR/launcher_scummvm.py leisure_suit_larry_6_vga_shape_up_or_slip_out lsl6-cd' > \
$INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/start.sh'
chmod +x $INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/start.sh'

cp $HOME'/.games_nebula/config/scummvmrc' \
$INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/'

echo "[lsl6-cd]
description=Leisure Suit Larry 6: Shape Up or Slip Out! (DOS/English)
gameid=sci
path=$INSTALL_DIR/leisure_suit_larry_6_vga_shape_up_or_slip_out/game
savepath=$INSTALL_DIR/leisure_suit_larry_6_vga_shape_up_or_slip_out/game" >> \
$INSTALL_DIR'/leisure_suit_larry_6_vga_shape_up_or_slip_out/scummvmrc'
