#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/last_express_the/tmp/app' $INSTALL_DIR'/last_express_the/game'
rm -R -f $INSTALL_DIR'/last_express_the/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/last_express_the
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/last_express_the/game \
$HOME/.games_nebula/games/.dosbox/last_express_the
python $NEBULA_DIR/launcher_dosbox.py last_express_the' > \
$INSTALL_DIR'/last_express_the/start.sh'
chmod +x $INSTALL_DIR'/last_express_the/start.sh'

echo "[autoexec]
@ECHO OFF
mount C $HOME/.games_nebula/games/.dosbox/last_express_the
mount D $HOME/.games_nebula/games/.dosbox/last_express_the/data -t cdrom
cls
c:
express.exe
exit" > $INSTALL_DIR'/last_express_the/dosbox_game.conf'
