#!/bin/bash

echo -e 'mkdir -p "$WINEPREFIX/drive_c/windows"
echo "[Info]
Version=v2.05
[SearchPaths]
HDDSearchPath=C:\Games\\'"$GAME_NAME"'
CDSearchPath=C:\Games\\'"$GAME_NAME"'
UninstallPath=C:\Games\\'"$GAME_NAME"'\unins000.exe" > \
"$WINEPREFIX/drive_c/windows/AlienNations_usa.ini"' >> \
"$ADDITIONS_FILE"
