#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/alien_nations/tmp/app' $INSTALL_DIR'/alien_nations/game'
rm -R -f $INSTALL_DIR'/alien_nations/tmp'

mkdir -p $DOWNLOAD_DIR'/_distr'

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' ]; then
	mkdir -p $DOWNLOAD_DIR'/_distr'
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' -C - \
	'https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe'
fi

if [ ! -f $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' ]; then
	mkdir -p $DOWNLOAD_DIR'/_distr'
	curl -L -o $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' -C - \
	'https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe'
fi

mkdir -p $HOME'/.cache/winetricks/directx9'
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_feb2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_feb2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi
if [ ! -f $HOME'/.cache/winetricks/directx9/directx_Jun2010_redist.exe' ]; then
	cp $DOWNLOAD_DIR'/_distr/directx_Jun2010_redist.exe' $HOME'/.cache/winetricks/directx9/'
fi

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py alien_nations Bin/AN.exe
xgamma -quiet -gamma 1' > $INSTALL_DIR'/alien_nations/start.sh'
chmod +x $INSTALL_DIR'/alien_nations/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

mkdir -p $WINEPREFIX_DIR/drive_c/windows/
echo "[Info]
Version=v2.05
[SearchPaths]
HDDSearchPath=$INSTALL_DIR_WIN\\alien_nations\game
CDSearchPath=$INSTALL_DIR_WIN\\alien_nations\game
UninstallPath=$INSTALL_DIR_WIN\\alien_nations\game\unins000.exe" > \
$WINEPREFIX_DIR/drive_c/windows/AlienNations_usa.ini

winetricks --gui quartz amstream

rm $WINEPREFIX_DIR/drive_c/Games/alien_nations
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/alien_nations/game \
$WINEPREFIX_DIR/drive_c/Games/alien_nations' > \
$INSTALL_DIR'/alien_nations/additions.sh'
chmod +x $INSTALL_DIR'/alien_nations/additions.sh'
