#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/giants_citizen_kabuto/tmp/app' $INSTALL_DIR'/giants_citizen_kabuto/game'
rm -R -f $INSTALL_DIR'/giants_citizen_kabuto/tmp/'*

if [ ! -f $DOWNLOAD_DIR'/_distr/citizen-kabuto-patch-1497-beta.zip' ]; then
	curl -L -o $DOWNLOAD_DIR'/_distr/citizen-kabuto-patch-1497-beta.zip' -C - \
	'http://community.pcgamingwiki.com/files/download/18-giants-citizen-kabuto-patch-1497-beta'
fi

unzip $DOWNLOAD_DIR'/_distr/citizen-kabuto-patch-1497-beta.zip' \
-d $INSTALL_DIR'/giants_citizen_kabuto/tmp'
cd $INSTALL_DIR'/giants_citizen_kabuto/tmp'
7z x -aoa 'GPatch1497F.exe'
rm 'GPatch1497F.exe'
rm -R -f '$PLUGINSDIR'
find $INSTALL_DIR'/giants_citizen_kabuto/game/Bin' -depth \
-exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
find $INSTALL_DIR'/giants_citizen_kabuto/tmp/bin' -depth \
-exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
cp -r $INSTALL_DIR'/giants_citizen_kabuto/tmp/'* $INSTALL_DIR'/giants_citizen_kabuto/game/'
mv $INSTALL_DIR'/giants_citizen_kabuto/game/bin/arpfix.gzp' \
$INSTALL_DIR'/giants_citizen_kabuto/game/bin/arpfix.gzp.bak'
rm -R -f $INSTALL_DIR'/giants_citizen_kabuto/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py giants_citizen_kabuto Giants.exe' > \
$INSTALL_DIR'/giants_citizen_kabuto/start.sh'
chmod +x $INSTALL_DIR'/giants_citizen_kabuto/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/giants_citizen_kabuto/game
$WINELOADER language_setup.exe' > $INSTALL_DIR'/giants_citizen_kabuto/settings.sh'
chmod +x $INSTALL_DIR'/giants_citizen_kabuto/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_CURRENT_USER\Software\PlanetMoon\Giants" /v \
"1.00.000" /t REG_SZ /d "" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\PlanetMoon\Giants" /v \
"DefPlayer" /t REG_SZ /d "Player1" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\PlanetMoon\Giants" /v \
"DestDir" /t REG_SZ /d $INSTALL_DIR_WIN\\\\giants_citizen_kabuto\\\\game\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\PlanetMoon\Giants" /v \
"Language" /t REG_SZ /d "9" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\PlanetMoon\Giants" /v \
"SrcDir" /t REG_SZ /d $INSTALL_DIR_WIN\\\\giants_citizen_kabuto\\\\game\\\\ /f

rm $WINEPREFIX_DIR/drive_c/Games/giants_citizen_kabuto
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/giants_citizen_kabuto/game \
$WINEPREFIX_DIR/drive_c/Games/giants_citizen_kabuto' > \
$INSTALL_DIR'/giants_citizen_kabuto/additions.sh'
chmod +x $INSTALL_DIR'/giants_citizen_kabuto/additions.sh'
