#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

get_file 'citizen-kabuto-patch-1497-beta.zip' \
'http://community.pcgamingwiki.com/files/download/18-giants-citizen-kabuto-patch-1497-beta'

7z x -aoa -o"$INSTALL_DIR/$GAME_NAME/tmp2" \
"$DOWNLOAD_DIR/_distr/$GAME_NAME/citizen-kabuto-patch-1497-beta.zip"

cd "$INSTALL_DIR/$GAME_NAME/tmp2"
7z x -aoa 'GPatch1497F.exe'
rm 'GPatch1497F.exe'
rm -R -f '$PLUGINSDIR'

find "$INSTALL_DIR/$GAME_NAME/game/Bin" -depth \
-exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \; \
& proc_timer $! "Renaming files to lowercase"
find "$INSTALL_DIR/$GAME_NAME/tmp2/bin" -depth \
-exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \; \
& proc_timer $! "Renaming files to lowercase"

cp -r "$INSTALL_DIR/$GAME_NAME/tmp2/"* "$INSTALL_DIR/$GAME_NAME/game/"
mv "$INSTALL_DIR/$GAME_NAME/game/bin/arpfix.gzp" \
"$INSTALL_DIR/$GAME_NAME/game/bin/arpfix.gzp.bak"
rm -R -f "$INSTALL_DIR/$GAME_NAME/tmp2"
