#!/bin/bash

echo -e '#!/bin/bash
python "$NEBULA_DIR/launcher_scummvm.py" '"$GAME_NAME"' teenagent' > \
"$START_FILE" && chmod +x "$START_FILE"

echo "[teenagent]
gameid=teenagent" > \
"$INSTALL_DIR/$GAME_NAME/scummvmrc"
