#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/flight_of_the_amazon_queen/tmp/app' \
$INSTALL_DIR'/flight_of_the_amazon_queen/game'
rm -R -f $INSTALL_DIR'/flight_of_the_amazon_queen/tmp'

echo -e '#!/bin/bash

INSTALL_DIR=$1
NEBULA_DIR=$2

SCUMMVMRC=$INSTALL_DIR/flight_of_the_amazon_queen/scummvmrc
readarray -t ARRAY <<<"$(cat "$SCUMMVMRC")"
LENGHT=${#ARRAY[@]}

for i in $(seq 1 $LENGHT); do
	if [[ ${ARRAY[i]} == "[queen]" ]]; then
		FIRST_LINE=$i
	fi
done

cp $HOME/.games_nebula/config/scummvmrc $SCUMMVMRC

for i in $(seq $FIRST_LINE $LENGHT); do 
	echo ${ARRAY[i]} >> "$SCUMMVMRC"
done

python $NEBULA_DIR/launcher_scummvm.py flight_of_the_amazon_queen queen' > \
$INSTALL_DIR'/flight_of_the_amazon_queen/start.sh'
chmod +x $INSTALL_DIR'/flight_of_the_amazon_queen/start.sh'

cp $HOME'/.games_nebula/config/scummvmrc' $INSTALL_DIR'/flight_of_the_amazon_queen/'

echo "[queen]
gameid=queen
description=Flight of the Amazon Queen (Talkie/DOS/English)
path=$INSTALL_DIR/flight_of_the_amazon_queen/game
savepath=$INSTALL_DIR/flight_of_the_amazon_queen/game" >> \
$INSTALL_DIR'/flight_of_the_amazon_queen/scummvmrc'
