#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/desperados_wanted_dead_or_alive/tmp/app' \
$INSTALL_DIR'/desperados_wanted_dead_or_alive/game'
rm -R -f $INSTALL_DIR'/desperados_wanted_dead_or_alive/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py desperados_wanted_dead_or_alive Game/game.exe' > \
$INSTALL_DIR'/desperados_wanted_dead_or_alive/start.sh'
chmod +x $INSTALL_DIR'/desperados_wanted_dead_or_alive/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/desperados_wanted_dead_or_alive
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/desperados_wanted_dead_or_alive/game \
$WINEPREFIX_DIR/drive_c/Games/desperados_wanted_dead_or_alive' > \
$INSTALL_DIR'/desperados_wanted_dead_or_alive/additions.sh'
chmod +x $INSTALL_DIR'/desperados_wanted_dead_or_alive/additions.sh'

zenity --question \
--text="Install screen resolution fix ?" \
--ok-label="Yes" --cancel-label="No"
if [ $? == 0 ]; then
if [ ! -f $DOWNLOAD_DIR'/_distr/desperados_wanted_dead_or_alive/Desperados_0.7z' ]; then
mkdir -p $DOWNLOAD_DIR/_distr/desperados_wanted_dead_or_alive
xdg-open $DOWNLOAD_DIR/_distr/desperados_wanted_dead_or_alive
sensible-browser "http://www.wsgf.org/dr/desperados-wanted-dead-or-alive/en" &
zenity --info --text \
"Download Desperados.7z and put it in\n<b>$DOWNLOAD_DIR/_distr/desperados_wanted_dead_or_alive/</b>\nThen click OK."
fi
7z x -aoa -o$INSTALL_DIR'/desperados_wanted_dead_or_alive/resfix/' \
$DOWNLOAD_DIR'/_distr/desperados_wanted_dead_or_alive/Desperados_0.7z'

echo '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR/resfix"
NEW_RES=$(zenity --list \
--hide-header \
--title "Desperados: Wanted Dead or Alive" \
--text "Select resolution:" \
--column "resoulution" $(ls))
if [ ! -f "$DIR/game/Game/game.exe.original" ]; then
    cp "$DIR/game/Game/game.exe" "$DIR/game/Game/game.exe.original"
fi
cp "$DIR/resfix/$NEW_RES/game.exe" "$DIR/game/Game/game.exe"' > \
$INSTALL_DIR'/desperados_wanted_dead_or_alive/settings.sh'
chmod +x $INSTALL_DIR'/desperados_wanted_dead_or_alive/settings.sh'
fi
