#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/the_nations_gold_edition/tmp/app' $INSTALL_DIR'/the_nations_gold_edition/game'
rm -R -f $INSTALL_DIR'/the_nations_gold_edition/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py the_nations_gold_edition bin/game.exe' > \
$INSTALL_DIR'/the_nations_gold_edition/start.sh'
chmod +x $INSTALL_DIR'/the_nations_gold_edition/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

cd $INSTALL_DIR/the_nations_gold_edition/game/tools
$WINELOADER setRegTrouble.exe' > $INSTALL_DIR'/the_nations_gold_edition/settings.sh'
chmod +x $INSTALL_DIR'/the_nations_gold_edition/settings.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINE_DIR=$2
WINEPREFIX_DIR=$3
INSTALL_DIR_WIN=$(echo Z:$INSTALL_DIR | sed -e s=/=\\\\\\\\=g)

if [ $WINE_DIR == "wine" ]; then
	export WINELOADER=$WINE_DIR
	export WINEPREFIX=$WINEPREFIX_DIR
else
	export WINE=$WINE_DIR/bin/wine
	export WINELOADER=$WINE_DIR/bin/wine
	export WINESERVER=$WINE_DIR/bin/wineserver
	export WINEDLLPATH=$WINE_DIR/lib
	export WINEPREFIX=$WINEPREFIX_DIR
fi

$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.channels" /t REG_DWORD /d "64" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.flags" /t REG_DWORD /d "7" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.master" /t REG_DWORD /d "255" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.music" /t REG_DWORD /d "191" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.sfx" /t REG_DWORD /d "255" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "audio.speech" /t REG_DWORD /d "255" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "fsgs.cdkey" /t REG_SZ /d "jh" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "fsgs.port" /t REG_DWORD /d "6112" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "lang" /t REG_SZ /d "en" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.bpp" /t REG_DWORD /d "16" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.device" /t REG_BINARY /d "0" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.flags" /t REG_DWORD /d "7" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.refresh" /t REG_DWORD /d "00000000" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.width" /t REG_DWORD /d "800" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" \
/v "video.height" /t REG_DWORD /d "600" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Troubleshoot" \
/v "EnableAGP" /t REG_DWORD /d "0" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Troubleshoot" \
/v "EnableVideoChange" /t REG_DWORD /d "0" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Troubleshoot" \
/v "TextureLimit" /t REG_DWORD /d "4000" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.campaigns" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\campaigns\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.crashlog" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\crash.log /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.install" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.invalidlog" /t REG_SZ /d "" /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.maps" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\maps\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.missions" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\missions\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.users" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\users\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon" /v \
"path.videos" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\data\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Paths" /v \
"Path0" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\ /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Paths" /v \
"Path1" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\music.ca /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Paths" /v \
"Path2" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\music2.ca /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Paths" /v \
"Path3" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\dv2.ca /f
$WINELOADER reg add "HKEY_CURRENT_USER\Software\JoWooD\DV2Addon\Paths" /v \
"Path4" /t REG_SZ /d $INSTALL_DIR_WIN\\\\the_nations_gold_edition\\\\game\\\\language.ca /f

rm $WINEPREFIX_DIR/drive_c/Games/the_nations_gold_edition
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/the_nations_gold_edition/game \
$WINEPREFIX_DIR/drive_c/Games/the_nations_gold_edition' > \
$INSTALL_DIR'/the_nations_gold_edition/additions.sh'
chmod +x $INSTALL_DIR'/the_nations_gold_edition/additions.sh'
