#!/bin/bash

DOWNLOAD_DIR=$1
INSTALL_DIR=$2

mv $INSTALL_DIR'/braid/tmp/data/noarch/'* $INSTALL_DIR'/braid/'
rm -R -f $INSTALL_DIR'/braid/tmp'
mv $INSTALL_DIR'/braid/start.sh' $INSTALL_DIR'/braid/start_gog.sh'

mkdir -p $DOWNLOAD_DIR'/_distr/braid'
if [ ! -f $DOWNLOAD_DIR'/_distr/braid/libxft2_2.3.2-1_i386.deb' ]; then
    curl -L -o $DOWNLOAD_DIR'/_distr/braid/libxft2_2.3.2-1_i386.deb' -C - \
    'http://ftp.debian.org/debian/pool/main/x/xft/libxft2_2.3.2-1_i386.deb'
fi

cp $DOWNLOAD_DIR'/_distr/braid/libxft2_2.3.2-1_i386.deb' $INSTALL_DIR'/braid/game/lib/'
cd $INSTALL_DIR'/braid/game/lib'
7z x './libxft2_2.3.2-1_i386.deb'
7z x './data.tar'
mv './usr/lib/i386-linux-gnu/'* ./
rm -r './usr' 'libxft2_2.3.2-1_i386.deb' 'data.tar'
rm './libXft.so.2'
mv $INSTALL_DIR'/braid/game/lib/libXft.so.2.3.2' $INSTALL_DIR'/braid/game/lib/libXft.so.2'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/game/lib"
cd "$DIR/game"
"./launcher.bin.x86"' > $INSTALL_DIR'/braid/start_gn.sh'
chmod +x $INSTALL_DIR'/braid/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py braid' > \
$INSTALL_DIR'/braid/start.sh'
chmod +x $INSTALL_DIR'/braid/start.sh'
