#!/bin/bash

source "$NEBULA_DIR/scripts/shell_functions.sh"

VER=$(python2 "$NEBULA_DIR/dialogs.py" list "DOSBox, Exult")

if [ "$VER" == "Exult" ]; then

mkdir -p "$INSTALL_DIR/exult/data"
rm -r "$INSTALL_DIR/exult/data/forgeofvirtue"
ln -s "$INSTALL_DIR/$GAME_NAME/game" "$INSTALL_DIR/exult/data/forgeofvirtue"

echo -e '#!/bin/bash
python2 "$NEBULA_DIR/launcher_native.py" '"$GAME_NAME" > \
"$START_FILE"

echo '#!/bin/bash
"$INSTALL_DIR/exult/bin/exult" -c "$INSTALL_DIR/exult/exult.cfg"' > \
"$START_GN_FILE" && chmod +x "$START_GN_FILE"

write_exult_cfg

get_exult

AUDIO=$(python2 "$NEBULA_DIR/dialogs.py" question "Audio Data packs")

if [ "$AUDIO" == "Yes" ]; then
get_exult_audio
fi

fi
