#!/bin/bash

INSTALL_DIR="$2"

mv "$INSTALL_DIR/battle_realms_winter_of_the_wolf/tmp/app" \
"$INSTALL_DIR/battle_realms_winter_of_the_wolf/game"
rm -R -f "$INSTALL_DIR/battle_realms_winter_of_the_wolf/tmp"
cp "$HOME/.games_nebula/scripts/goglib/battle_realms_winter_of_the_wolf/settings.py" \
"$INSTALL_DIR/battle_realms_winter_of_the_wolf/"
chmod +x "$INSTALL_DIR/battle_realms_winter_of_the_wolf/settings.py"

echo -e '#!/bin/bash
NEBULA_DIR="$2"
python "$NEBULA_DIR/launcher_wine.py" battle_realms_winter_of_the_wolf Battle_Realms_F.exe
xgamma -gamma 1' > "$INSTALL_DIR/battle_realms_winter_of_the_wolf/start.sh"
chmod +x "$INSTALL_DIR/battle_realms_winter_of_the_wolf/start.sh"

echo -e '#!/bin/bash
INSTALL_DIR="$1"
NEBULA_DIR="$4"
python2 "$INSTALL_DIR/battle_realms_winter_of_the_wolf/settings.py" \
"$NEBULA_DIR"' > "$INSTALL_DIR/battle_realms_winter_of_the_wolf/settings.sh"
chmod +x "$INSTALL_DIR/battle_realms_winter_of_the_wolf/settings.sh"
