#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/akalabeth_world_of_doom/tmp/data/noarch/data' \
$INSTALL_DIR'/akalabeth_world_of_doom/game'
rm -R -f $INSTALL_DIR'/akalabeth_world_of_doom/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/akalabeth_world_of_doom
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/akalabeth_world_of_doom/game \
$HOME/.games_nebula/games/.dosbox/akalabeth_world_of_doom
python $NEBULA_DIR/launcher_dosbox.py akalabeth_world_of_doom' > \
$INSTALL_DIR'/akalabeth_world_of_doom/start.sh'
chmod +x $INSTALL_DIR'/akalabeth_world_of_doom/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/akalabeth_world_of_doom
c:
cls
aklabeth
cls
exit" > $INSTALL_DIR'/akalabeth_world_of_doom/dosbox_game.conf'
