#!/bin/bash

INSTALL_DIR=$2
NEBULA_DIR=$3

python2 $NEBULA_DIR'/modules/goglib_get_banner_2.py' \
'master_of_orion_classic' \
'https://images-1.gog.com/b32a7e40965d2ae1149b87d8b553e811f1c8330dc4a9c5e75b85da88cc9b6ee2.jpg' \
$HOME'/.games_nebula/images/goglib_banners'

mv $INSTALL_DIR'/master_of_orion_classic/tmp/data/noarch/data' $INSTALL_DIR'/master_of_orion_classic/game'
rm -R -f $INSTALL_DIR'/master_of_orion_classic/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/master_of_orion_classic
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/master_of_orion_classic/game \
$HOME/.games_nebula/games/.dosbox/master_of_orion_classic
python $NEBULA_DIR/launcher_dosbox.py master_of_orion_classic' > \
$INSTALL_DIR'/master_of_orion_classic/start.sh'
chmod +x $INSTALL_DIR'/master_of_orion_classic/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/master_of_orion_classic
c:
cls
orion.exe
cls
exit" > $INSTALL_DIR'/master_of_orion_classic/dosbox_game.conf'
