#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/the_silver_case_demo/tmp/app' $INSTALL_DIR'/the_silver_case_demo/game'
rm -R -f $INSTALL_DIR'/the_silver_case_demo/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py the_silver_case_demo TheSilverCase_Trial.exe' > \
$INSTALL_DIR'/the_silver_case_demo/start.sh'
chmod +x $INSTALL_DIR'/the_silver_case_demo/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/the_silver_case_demo
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/the_silver_case_demo/game \
$WINEPREFIX_DIR/drive_c/Games/the_silver_case_demo' > \
$INSTALL_DIR'/the_silver_case_demo/additions.sh'
chmod +x $INSTALL_DIR'/the_silver_case_demo/additions.sh'
