#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/eschalon_book_i/tmp/data/noarch/'* $INSTALL_DIR'/eschalon_book_i/'
rm -R -f $INSTALL_DIR'/eschalon_book_i/tmp'
mv $INSTALL_DIR'/eschalon_book_i/start.sh' $INSTALL_DIR'/eschalon_book_i/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./Eschalon Book I"' > $INSTALL_DIR'/eschalon_book_i/start_gn.sh'
chmod +x $INSTALL_DIR'/eschalon_book_i/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py eschalon_book_i' > \
$INSTALL_DIR'/eschalon_book_i/start.sh'
chmod +x $INSTALL_DIR'/eschalon_book_i/start.sh'
