#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/simcity_2000_special_edition/tmp/app' $INSTALL_DIR'/simcity_2000_special_edition/game'
rm -R -f $INSTALL_DIR'/simcity_2000_special_edition/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/simcity_2000_special_edition/game \
$HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition
python $NEBULA_DIR/launcher_dosbox.py simcity_2000_special_edition' > \
$INSTALL_DIR'/simcity_2000_special_edition/start.sh'
chmod +x $INSTALL_DIR'/simcity_2000_special_edition/start.sh'

echo "[autoexec]
@echo off
mount C $HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition
imgmount d $HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition/SC2000SE.DAT -t iso
c:
cls

echo.
echo.
ECHO  --------------------------------- 
ECHO  SimCity 2000                 
ECHO  --------------------------------- 
ECHO  1) SimCity 2000             
ECHO  2) SimCity 2000 Urban Renewal Kit              
ECHO  --------------------------------- 
ECHO  3) exit program                  
ECHO  --------------------------------- 
echo.
echo.

choice /c123 /s Which application do you want to run? [1-3]: /n 
if errorlevel 3 goto exit
if errorlevel 2 goto scurk
if errorlevel 1 goto sc2000

:sc2000
cls
call SC2000.BAT
exit

:scurk
cls
SCURK.COM
exit

:exit
exit" > $INSTALL_DIR'/simcity_2000_special_edition/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition
imgmount d $HOME/.games_nebula/games/.dosbox/simcity_2000_special_edition/SC2000SE.DAT -t iso
c:
cls
install.exe
exit" > $INSTALL_DIR'/simcity_2000_special_edition/dosbox_settings.conf'
