#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/stargunner/tmp/data/noarch/data' $INSTALL_DIR'/stargunner/game'
rm -R -f $INSTALL_DIR'/stargunner/tmp'

echo '#!/bin/bash
INSTALL_DIR=$1
NEBULA_DIR=$2
rm $HOME/.games_nebula/games/.dosbox/stargunner
mkdir -p $HOME/.games_nebula/games/.dosbox
ln -s $INSTALL_DIR/stargunner/game \
$HOME/.games_nebula/games/.dosbox/stargunner
python $NEBULA_DIR/launcher_dosbox.py stargunner' > \
$INSTALL_DIR'/stargunner/start.sh'
chmod +x $INSTALL_DIR'/stargunner/start.sh'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/stargunner
c:
cls
STARGUN.exe
exit" > $INSTALL_DIR'/stargunner/dosbox_game.conf'

echo "[autoexec]
mount C $HOME/.games_nebula/games/.dosbox/stargunner
c:
cls
SETUP.exe
exit" > $INSTALL_DIR'/stargunner/dosbox_settings.conf'
