#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/silence_demo/tmp/game' $INSTALL_DIR'/silence_demo/game'
rm -R -f $INSTALL_DIR'/silence_demo/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py silence_demo/game Silence.exe' > \
$INSTALL_DIR'/silence_demo/start.sh'
chmod +x $INSTALL_DIR'/silence_demo/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/silence_demo
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/silence_demo/game \
$WINEPREFIX_DIR/drive_c/Games/silence_demo' > \
$INSTALL_DIR'/silence_demo/additions.sh'
chmod +x $INSTALL_DIR'/silence_demo/additions.sh'
