#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/shadow_warrior_classic_redux/tmp/app' \
$INSTALL_DIR'/shadow_warrior_classic_redux/game'
rm -R -f $INSTALL_DIR'/shadow_warrior_classic_redux/tmp'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_wine.py shadow_warrior_classic_redux swcr.exe' > \
$INSTALL_DIR'/shadow_warrior_classic_redux/start.sh'
chmod +x $INSTALL_DIR'/shadow_warrior_classic_redux/start.sh'

echo -e '#!/bin/bash
INSTALL_DIR=$1
WINEPREFIX_DIR=$3
rm $WINEPREFIX_DIR/drive_c/Games/shadow_warrior_classic_redux
mkdir -p $WINEPREFIX_DIR/drive_c/Games
ln -s $INSTALL_DIR/shadow_warrior_classic_redux/game \
$WINEPREFIX_DIR/drive_c/Games/shadow_warrior_classic_redux' > \
$INSTALL_DIR'/shadow_warrior_classic_redux/additions.sh'
chmod +x $INSTALL_DIR'/shadow_warrior_classic_redux/additions.sh'
