#!/bin/bash

INSTALL_DIR=$2

mv $INSTALL_DIR'/fran_bow/tmp/data/noarch/'* $INSTALL_DIR'/fran_bow/'
rm -R -f $INSTALL_DIR'/fran_bow/tmp'
mv $INSTALL_DIR'/fran_bow/start.sh' $INSTALL_DIR'/fran_bow/start_gog.sh'

echo -e '#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH:$DIR/lib"
cd "$DIR/game"
"./runner"' > $INSTALL_DIR'/fran_bow/start_gn.sh'
chmod +x $INSTALL_DIR'/fran_bow/start_gn.sh'

echo -e '#!/bin/bash
NEBULA_DIR=$2
python $NEBULA_DIR/launcher_native.py fran_bow' > \
$INSTALL_DIR'/fran_bow/start.sh'
chmod +x $INSTALL_DIR'/fran_bow/start.sh'
